// GENERATED by scripts/ingest/gen_contracts.py from scripts/ingest/schema.py — do not edit.

/** One row per ingested source: query, release, checksum, licence, coverage. */
export interface DatasetManifestRow {
  id: string;
  sourceName: string;
  category: string;
  sourceUrls: string;
  release: string;
  query: string;
  retrievedAt: string;
  checksum: string;
  license: string;
  attribution: string;
  coverage: string;
  units: string;
  frame: string;
  validationStatus: string;
  rowCount: number;
  tables: string;
  note: string;
}

/** JPL Horizons heliocentric state vectors at the pinned epoch plus SPICE constants. */
export interface HorizonsBodyRow {
  id: string;
  name: string;
  naifId: number;
  kind: string;
  parentId: string;
  xM: number;
  yM: number;
  zM: number;
  vxMps: number;
  vyMps: number;
  vzMps: number;
  epochTdb: string;
  epochJd: number;
  frame: string;
  center: string;
  radiusKm: number | null;
  gmKm3S2: number | null;
  massKg: number | null;
  semiMajorAxisAu: number | null;
  eccentricity: number | null;
  inclinationDeg: number | null;
  orbitPeriodDays: number | null;
  rotationPeriodHours: number | null;
  obliquityDeg: number | null;
  colorHex: string;
  evidenceKind: string;
}

/** Sampled orbit tracks from Horizons (heliocentric for planets, parent-centric for moons). */
export interface OrbitSampleRow {
  id: string;
  bodyId: string;
  center: string;
  idx: number;
  jdTdb: number;
  xM: number;
  yM: number;
  zM: number;
}

/** NAIF SPICE generic PCK/GM kernel values per body. */
export interface SpiceConstantRow {
  id: string;
  naifId: number;
  name: string;
  radiusAKm: number | null;
  radiusBKm: number | null;
  radiusCKm: number | null;
  gmKm3S2: number | null;
  poleRaDeg: number | null;
  poleDecDeg: number | null;
  pmW0Deg: number | null;
  pmRateDegDay: number | null;
  kernels: string;
}

/** NASA NSSDC Planetary Fact Sheet values (reference physical data). */
export interface PlanetFactRow {
  id: string;
  name: string;
  massE24Kg: number | null;
  diameterKm: number | null;
  densityKgM3: number | null;
  gravityMs2: number | null;
  escapeVelocityKms: number | null;
  rotationPeriodHours: number | null;
  dayLengthHours: number | null;
  distanceFromSunE6Km: number | null;
  orbitalPeriodDays: number | null;
  orbitalVelocityKms: number | null;
  obliquityDeg: number | null;
  meanTemperatureC: number | null;
  surfacePressureBars: number | null;
  moonCount: number | null;
  ringSystem: string;
  globalMagneticField: string;
}

/** Planet surface maps: PDS archive elevation grids and labelled illustrative colour maps. */
export interface PlanetTextureRow {
  id: string;
  bodyId: string;
  kind: string;
  path: string;
  width: number;
  height: number;
  source: string;
  sourceProductId: string;
  sourceUrl: string;
  projection: string;
  license: string;
  evidenceKind: string;
}

/** NASA Earthdata (CMR discovery + GIBS imagery) global layers. */
export interface EarthLayerRow {
  id: string;
  title: string;
  gibsLayer: string;
  cmrConceptId: string;
  collectionShortName: string;
  timeRange: string;
  path: string;
  units: string;
  legend: string;
  evidenceKind: string;
}

/** Natural Earth populated places (1:110m). */
export interface EarthCityRow {
  id: string;
  name: string;
  country: string;
  latDeg: number;
  lonDeg: number;
  population: number | null;
  rank: number | null;
}

/** World primary energy and electricity generation (Our World in Data / Energy Institute). */
export interface EnergyRecordRow {
  id: string;
  entity: string;
  year: number;
  metric: string;
  source: string;
  valueTwh: number;
}

/** NOAA NCEI global land+ocean surface temperature anomaly. */
export interface ClimateAnomalyRow {
  id: string;
  year: number;
  anomalyC: number;
  baseline: string;
}

/** USGS FDSN event catalogue (bounded query). */
export interface EarthquakeRow {
  id: string;
  timeIso: string;
  magnitude: number;
  place: string;
  latDeg: number;
  lonDeg: number;
  depthKm: number;
  eventType: string;
}

/** ESA Gaia DR3 quality-filtered astrometry (parallax_over_error > 10, RUWE < 1.4). */
export interface GaiaStarRow {
  sourceId: string;
  raDeg: number;
  decDeg: number;
  parallaxMas: number;
  parallaxErrorMas: number;
  pmraMasYr: number | null;
  pmdecMasYr: number | null;
  radialVelocityKms: number | null;
  gMag: number;
  bpRp: number | null;
  teffK: number | null;
  luminosityLsun: number | null;
  distancePc: number;
  xPc: number;
  yPc: number;
  zPc: number;
  glDeg: number;
  gbDeg: number;
  ruwe: number | null;
  refEpoch: number;
  sample: string;
}

/** Bright named stars (IAU WGSN names) with SIMBAD/Hipparcos astrometry. */
export interface NamedStarRow {
  id: string;
  name: string;
  simbadId: string;
  raDeg: number;
  decDeg: number;
  parallaxMas: number | null;
  vMag: number | null;
  spType: string;
  distancePc: number | null;
  xPc: number | null;
  yPc: number | null;
  zPc: number | null;
  gaiaDr3Id: string;
  source: string;
}

/** NASA Exoplanet Archive pscomppars composite parameters (all confirmed planets). */
export interface ExoplanetSystemRow {
  plName: string;
  hostname: string;
  raDeg: number;
  decDeg: number;
  distancePc: number | null;
  orbitalPeriodDays: number | null;
  semiMajorAxisAu: number | null;
  radiusEarth: number | null;
  massEarth: number | null;
  eqTempK: number | null;
  eccentricity: number | null;
  insolationEarth: number | null;
  stTeffK: number | null;
  stRadiusSun: number | null;
  stMassSun: number | null;
  stLumLog: number | null;
  discoveryMethod: string;
  discoveryYear: number | null;
  sysPlanetCount: number | null;
  gaiaDr3Id: string;
  xPc: number | null;
  yPc: number | null;
  zPc: number | null;
}

/** SDSS DR18 spectroscopic galaxies with Planck18 comoving distances. */
export interface SdssGalaxyRow {
  specObjId: string;
  raDeg: number;
  decDeg: number;
  redshift: number;
  redshiftErr: number;
  subclass: string;
  petroMagR: number | null;
  comovingMpc: number;
  xMpc: number;
  yMpc: number;
  zMpc: number;
}

/** HEASARC LMXB/HMXB catalogues. An X-ray binary is not automatically a black hole. */
export interface XrayBinaryRow {
  id: string;
  name: string;
  raDeg: number;
  decDeg: number;
  glDeg: number;
  gbDeg: number;
  kind: string;
  distanceKpc: number | null;
  orbitalPeriodDays: number | null;
  compactObject: string;
  catalog: string;
}

/** Human Cell Atlas (Azul) projects touching blood / bone-marrow erythroid context. */
export interface HcaProjectRow {
  id: string;
  title: string;
  organs: string;
  cellCount: number | null;
  donorCount: number | null;
  cellTypes: string;
  assays: string;
  url: string;
}

/** NCBI Gene + Ensembl gene/transcript identifiers. */
export interface GeneRecordRow {
  id: string;
  geneId: string;
  symbol: string;
  description: string;
  chromosome: string;
  mapLocation: string;
  assembly: string;
  startPos: number | null;
  endPos: number | null;
  strand: number;
  ensemblGeneId: string;
  refseqTranscript: string;
  refseqProtein: string;
  ensemblTranscript: string;
  summary: string;
}

/** Coding and protein sequences (NCBI nuccore/protein and Ensembl). */
export interface SequenceRecordRow {
  accession: string;
  geneSymbol: string;
  kind: string;
  length: number;
  sequence: string;
  source: string;
  release: string;
}

/** Curated HBB variants: Ensembl VEP-style consequence + ClinVar classification. */
export interface VariantRecordRow {
  id: string;
  geneSymbol: string;
  rsId: string;
  clinvarId: string;
  hgvsC: string;
  hgvsP: string;
  proteinChange: string;
  chromosome: string;
  positionGrch38: number | null;
  refAllele: string;
  altAllele: string;
  cdsPosition: number | null;
  codonRef: string;
  codonAlt: string;
  consequence: string;
  clinicalSignificance: string;
  reviewStatus: string;
  conditions: string;
  source: string;
}

/** RCSB PDB entry metadata. */
export interface PdbEntryRow {
  id: string;
  title: string;
  method: string;
  resolutionA: number | null;
  depositDate: string;
  organism: string;
  description: string;
  atomCount: number;
  chains: string;
  ligands: string;
}

/** mmCIF atom_site rows (model 1, first altloc, waters dropped). Coordinates in Å. */
export interface PdbAtomRow {
  id: string;
  entryId: string;
  serial: number;
  chain: string;
  resSeq: number;
  resName: string;
  atomName: string;
  element: string;
  x: number;
  y: number;
  z: number;
  occupancy: number;
  bFactor: number;
  hetero: boolean;
}

/** Helix / strand ranges from mmCIF struct_conf and struct_sheet_range. */
export interface PdbSecondaryRow {
  id: string;
  entryId: string;
  chain: string;
  kind: string;
  startResSeq: number;
  endResSeq: number;
}

/** PubChem compounds with 3D conformers. */
export interface MoleculeRow {
  cid: number;
  name: string;
  formula: string;
  molecularWeight: number;
  iupacName: string;
  smiles: string;
  atomCount: number;
  bondCount: number;
  conformer: string;
}

/** PubChem 3D conformer atoms (Å). */
export interface MoleculeAtomRow {
  id: string;
  cid: number;
  idx: number;
  element: string;
  x: number;
  y: number;
  z: number;
}

/** PubChem 3D conformer bonds. */
export interface MoleculeBondRow {
  id: string;
  cid: number;
  a1: number;
  a2: number;
  order: number;
}

/** NIST ASD evaluated energy levels. */
export interface NistLevelRow {
  id: string;
  species: string;
  configuration: string;
  term: string;
  j: string;
  energyEv: number;
  uncertaintyEv: number | null;
  n: number | null;
  l: number | null;
  reference: string;
}

/** NIST ASD spectral lines with Einstein A coefficients where evaluated. */
export interface NistLineRow {
  id: string;
  species: string;
  wavelengthVacNm: number;
  akiPerS: number | null;
  accuracy: string;
  eiEv: number;
  ekEv: number;
  lowerConf: string;
  lowerTerm: string;
  lowerJ: string;
  upperConf: string;
  upperTerm: string;
  upperJ: string;
  lineType: string;
}

/** NIST ASD ground-state ionization energies. */
export interface IonizationEnergyRow {
  species: string;
  element: string;
  ionizationEv: number;
  reference: string;
}

/** IAEA LiveChart ground states (ENSDF / NUBASE / AME2020). */
export interface NuclideRow {
  id: string;
  z: number;
  n: number;
  a: number;
  symbol: string;
  halfLifeS: number | null;
  halfLifeText: string;
  stable: boolean;
  spinParity: string;
  decayModes: string;
  massExcessKeV: number | null;
  bindingPerNucleonKeV: number | null;
  abundancePct: number | null;
  qBetaMinusKeV: number | null;
  qEcKeV: number | null;
}

/** IAEA LiveChart / ENSDF excited levels for the traversal nuclides. */
export interface NuclearLevelRow {
  id: string;
  nuclide: string;
  energyKeV: number;
  spinParity: string;
  halfLifeText: string;
  source: string;
}

/** IAEA LiveChart / ENSDF decay radiation (beta+, gamma, X-ray) for traversal nuclides. */
export interface DecayRadiationRow {
  id: string;
  parent: string;
  decayMode: string;
  radiationType: string;
  energyKeV: number;
  intensityPct: number | null;
  source: string;
}

/** Particle Data Group API database: summary-table masses, widths, lifetimes. */
export interface PdgParticleRow {
  id: string;
  mcId: number;
  name: string;
  pdgId: string;
  charge: number;
  spin: string;
  parity: string;
  cParity: string;
  isospin: string;
  massMeV: number | null;
  massErrMeV: number | null;
  widthMeV: number | null;
  lifetimeS: number | null;
  category: string;
  edition: string;
}

export interface ScienceTables {
  dataset_manifest: DatasetManifestRow[];
  horizons_body: HorizonsBodyRow[];
  orbit_sample: OrbitSampleRow[];
  spice_constant: SpiceConstantRow[];
  planet_fact: PlanetFactRow[];
  planet_texture: PlanetTextureRow[];
  earth_layer: EarthLayerRow[];
  earth_city: EarthCityRow[];
  energy_record: EnergyRecordRow[];
  climate_anomaly: ClimateAnomalyRow[];
  earthquake: EarthquakeRow[];
  gaia_star: GaiaStarRow[];
  named_star: NamedStarRow[];
  exoplanet_system: ExoplanetSystemRow[];
  sdss_galaxy: SdssGalaxyRow[];
  xray_binary: XrayBinaryRow[];
  hca_project: HcaProjectRow[];
  gene_record: GeneRecordRow[];
  sequence_record: SequenceRecordRow[];
  variant_record: VariantRecordRow[];
  pdb_entry: PdbEntryRow[];
  pdb_atom: PdbAtomRow[];
  pdb_secondary: PdbSecondaryRow[];
  molecule: MoleculeRow[];
  molecule_atom: MoleculeAtomRow[];
  molecule_bond: MoleculeBondRow[];
  nist_level: NistLevelRow[];
  nist_line: NistLineRow[];
  ionization_energy: IonizationEnergyRow[];
  nuclide: NuclideRow[];
  nuclear_level: NuclearLevelRow[];
  decay_radiation: DecayRadiationRow[];
  pdg_particle: PdgParticleRow[];
}

export type ScienceTableName = keyof ScienceTables;

export const SCIENCE_TABLE_NAMES: ScienceTableName[] = [
  'dataset_manifest',
  'horizons_body',
  'orbit_sample',
  'spice_constant',
  'planet_fact',
  'planet_texture',
  'earth_layer',
  'earth_city',
  'energy_record',
  'climate_anomaly',
  'earthquake',
  'gaia_star',
  'named_star',
  'exoplanet_system',
  'sdss_galaxy',
  'xray_binary',
  'hca_project',
  'gene_record',
  'sequence_record',
  'variant_record',
  'pdb_entry',
  'pdb_atom',
  'pdb_secondary',
  'molecule',
  'molecule_atom',
  'molecule_bond',
  'nist_level',
  'nist_line',
  'ionization_energy',
  'nuclide',
  'nuclear_level',
  'decay_radiation',
  'pdg_particle',
];

/** Column types per table; '?' marks nullable (SpacetimeDB option) columns. */
export const SCIENCE_COLUMNS: Record<ScienceTableName, [string, string][]> = {
  dataset_manifest: [['id', 'str'], ['sourceName', 'str'], ['category', 'str'], ['sourceUrls', 'str'], ['release', 'str'], ['query', 'str'], ['retrievedAt', 'str'], ['checksum', 'str'], ['license', 'str'], ['attribution', 'str'], ['coverage', 'str'], ['units', 'str'], ['frame', 'str'], ['validationStatus', 'str'], ['rowCount', 'u32'], ['tables', 'str'], ['note', 'str']],
  horizons_body: [['id', 'str'], ['name', 'str'], ['naifId', 'i32'], ['kind', 'str'], ['parentId', 'str'], ['xM', 'f64'], ['yM', 'f64'], ['zM', 'f64'], ['vxMps', 'f64'], ['vyMps', 'f64'], ['vzMps', 'f64'], ['epochTdb', 'str'], ['epochJd', 'f64'], ['frame', 'str'], ['center', 'str'], ['radiusKm', 'f64?'], ['gmKm3S2', 'f64?'], ['massKg', 'f64?'], ['semiMajorAxisAu', 'f64?'], ['eccentricity', 'f64?'], ['inclinationDeg', 'f64?'], ['orbitPeriodDays', 'f64?'], ['rotationPeriodHours', 'f64?'], ['obliquityDeg', 'f64?'], ['colorHex', 'str'], ['evidenceKind', 'str']],
  orbit_sample: [['id', 'str'], ['bodyId', 'str'], ['center', 'str'], ['idx', 'u32'], ['jdTdb', 'f64'], ['xM', 'f64'], ['yM', 'f64'], ['zM', 'f64']],
  spice_constant: [['id', 'str'], ['naifId', 'i32'], ['name', 'str'], ['radiusAKm', 'f64?'], ['radiusBKm', 'f64?'], ['radiusCKm', 'f64?'], ['gmKm3S2', 'f64?'], ['poleRaDeg', 'f64?'], ['poleDecDeg', 'f64?'], ['pmW0Deg', 'f64?'], ['pmRateDegDay', 'f64?'], ['kernels', 'str']],
  planet_fact: [['id', 'str'], ['name', 'str'], ['massE24Kg', 'f64?'], ['diameterKm', 'f64?'], ['densityKgM3', 'f64?'], ['gravityMs2', 'f64?'], ['escapeVelocityKms', 'f64?'], ['rotationPeriodHours', 'f64?'], ['dayLengthHours', 'f64?'], ['distanceFromSunE6Km', 'f64?'], ['orbitalPeriodDays', 'f64?'], ['orbitalVelocityKms', 'f64?'], ['obliquityDeg', 'f64?'], ['meanTemperatureC', 'f64?'], ['surfacePressureBars', 'f64?'], ['moonCount', 'u32?'], ['ringSystem', 'str'], ['globalMagneticField', 'str']],
  planet_texture: [['id', 'str'], ['bodyId', 'str'], ['kind', 'str'], ['path', 'str'], ['width', 'u32'], ['height', 'u32'], ['source', 'str'], ['sourceProductId', 'str'], ['sourceUrl', 'str'], ['projection', 'str'], ['license', 'str'], ['evidenceKind', 'str']],
  earth_layer: [['id', 'str'], ['title', 'str'], ['gibsLayer', 'str'], ['cmrConceptId', 'str'], ['collectionShortName', 'str'], ['timeRange', 'str'], ['path', 'str'], ['units', 'str'], ['legend', 'str'], ['evidenceKind', 'str']],
  earth_city: [['id', 'str'], ['name', 'str'], ['country', 'str'], ['latDeg', 'f64'], ['lonDeg', 'f64'], ['population', 'f64?'], ['rank', 'u32?']],
  energy_record: [['id', 'str'], ['entity', 'str'], ['year', 'u32'], ['metric', 'str'], ['source', 'str'], ['valueTwh', 'f64']],
  climate_anomaly: [['id', 'str'], ['year', 'u32'], ['anomalyC', 'f64'], ['baseline', 'str']],
  earthquake: [['id', 'str'], ['timeIso', 'str'], ['magnitude', 'f64'], ['place', 'str'], ['latDeg', 'f64'], ['lonDeg', 'f64'], ['depthKm', 'f64'], ['eventType', 'str']],
  gaia_star: [['sourceId', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['parallaxMas', 'f64'], ['parallaxErrorMas', 'f64'], ['pmraMasYr', 'f64?'], ['pmdecMasYr', 'f64?'], ['radialVelocityKms', 'f64?'], ['gMag', 'f64'], ['bpRp', 'f64?'], ['teffK', 'f64?'], ['luminosityLsun', 'f64?'], ['distancePc', 'f64'], ['xPc', 'f64'], ['yPc', 'f64'], ['zPc', 'f64'], ['glDeg', 'f64'], ['gbDeg', 'f64'], ['ruwe', 'f64?'], ['refEpoch', 'f64'], ['sample', 'str']],
  named_star: [['id', 'str'], ['name', 'str'], ['simbadId', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['parallaxMas', 'f64?'], ['vMag', 'f64?'], ['spType', 'str'], ['distancePc', 'f64?'], ['xPc', 'f64?'], ['yPc', 'f64?'], ['zPc', 'f64?'], ['gaiaDr3Id', 'str'], ['source', 'str']],
  exoplanet_system: [['plName', 'str'], ['hostname', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['distancePc', 'f64?'], ['orbitalPeriodDays', 'f64?'], ['semiMajorAxisAu', 'f64?'], ['radiusEarth', 'f64?'], ['massEarth', 'f64?'], ['eqTempK', 'f64?'], ['eccentricity', 'f64?'], ['insolationEarth', 'f64?'], ['stTeffK', 'f64?'], ['stRadiusSun', 'f64?'], ['stMassSun', 'f64?'], ['stLumLog', 'f64?'], ['discoveryMethod', 'str'], ['discoveryYear', 'u32?'], ['sysPlanetCount', 'u32?'], ['gaiaDr3Id', 'str'], ['xPc', 'f64?'], ['yPc', 'f64?'], ['zPc', 'f64?']],
  sdss_galaxy: [['specObjId', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['redshift', 'f64'], ['redshiftErr', 'f64'], ['subclass', 'str'], ['petroMagR', 'f64?'], ['comovingMpc', 'f64'], ['xMpc', 'f64'], ['yMpc', 'f64'], ['zMpc', 'f64']],
  xray_binary: [['id', 'str'], ['name', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['glDeg', 'f64'], ['gbDeg', 'f64'], ['kind', 'str'], ['distanceKpc', 'f64?'], ['orbitalPeriodDays', 'f64?'], ['compactObject', 'str'], ['catalog', 'str']],
  hca_project: [['id', 'str'], ['title', 'str'], ['organs', 'str'], ['cellCount', 'f64?'], ['donorCount', 'u32?'], ['cellTypes', 'str'], ['assays', 'str'], ['url', 'str']],
  gene_record: [['id', 'str'], ['geneId', 'str'], ['symbol', 'str'], ['description', 'str'], ['chromosome', 'str'], ['mapLocation', 'str'], ['assembly', 'str'], ['startPos', 'u32?'], ['endPos', 'u32?'], ['strand', 'i32'], ['ensemblGeneId', 'str'], ['refseqTranscript', 'str'], ['refseqProtein', 'str'], ['ensemblTranscript', 'str'], ['summary', 'str']],
  sequence_record: [['accession', 'str'], ['geneSymbol', 'str'], ['kind', 'str'], ['length', 'u32'], ['sequence', 'str'], ['source', 'str'], ['release', 'str']],
  variant_record: [['id', 'str'], ['geneSymbol', 'str'], ['rsId', 'str'], ['clinvarId', 'str'], ['hgvsC', 'str'], ['hgvsP', 'str'], ['proteinChange', 'str'], ['chromosome', 'str'], ['positionGrch38', 'u32?'], ['refAllele', 'str'], ['altAllele', 'str'], ['cdsPosition', 'u32?'], ['codonRef', 'str'], ['codonAlt', 'str'], ['consequence', 'str'], ['clinicalSignificance', 'str'], ['reviewStatus', 'str'], ['conditions', 'str'], ['source', 'str']],
  pdb_entry: [['id', 'str'], ['title', 'str'], ['method', 'str'], ['resolutionA', 'f64?'], ['depositDate', 'str'], ['organism', 'str'], ['description', 'str'], ['atomCount', 'u32'], ['chains', 'str'], ['ligands', 'str']],
  pdb_atom: [['id', 'str'], ['entryId', 'str'], ['serial', 'u32'], ['chain', 'str'], ['resSeq', 'i32'], ['resName', 'str'], ['atomName', 'str'], ['element', 'str'], ['x', 'f64'], ['y', 'f64'], ['z', 'f64'], ['occupancy', 'f64'], ['bFactor', 'f64'], ['hetero', 'bool']],
  pdb_secondary: [['id', 'str'], ['entryId', 'str'], ['chain', 'str'], ['kind', 'str'], ['startResSeq', 'i32'], ['endResSeq', 'i32']],
  molecule: [['cid', 'u32'], ['name', 'str'], ['formula', 'str'], ['molecularWeight', 'f64'], ['iupacName', 'str'], ['smiles', 'str'], ['atomCount', 'u32'], ['bondCount', 'u32'], ['conformer', 'str']],
  molecule_atom: [['id', 'str'], ['cid', 'u32'], ['idx', 'u32'], ['element', 'str'], ['x', 'f64'], ['y', 'f64'], ['z', 'f64']],
  molecule_bond: [['id', 'str'], ['cid', 'u32'], ['a1', 'u32'], ['a2', 'u32'], ['order', 'u32']],
  nist_level: [['id', 'str'], ['species', 'str'], ['configuration', 'str'], ['term', 'str'], ['j', 'str'], ['energyEv', 'f64'], ['uncertaintyEv', 'f64?'], ['n', 'u32?'], ['l', 'u32?'], ['reference', 'str']],
  nist_line: [['id', 'str'], ['species', 'str'], ['wavelengthVacNm', 'f64'], ['akiPerS', 'f64?'], ['accuracy', 'str'], ['eiEv', 'f64'], ['ekEv', 'f64'], ['lowerConf', 'str'], ['lowerTerm', 'str'], ['lowerJ', 'str'], ['upperConf', 'str'], ['upperTerm', 'str'], ['upperJ', 'str'], ['lineType', 'str']],
  ionization_energy: [['species', 'str'], ['element', 'str'], ['ionizationEv', 'f64'], ['reference', 'str']],
  nuclide: [['id', 'str'], ['z', 'u32'], ['n', 'u32'], ['a', 'u32'], ['symbol', 'str'], ['halfLifeS', 'f64?'], ['halfLifeText', 'str'], ['stable', 'bool'], ['spinParity', 'str'], ['decayModes', 'str'], ['massExcessKeV', 'f64?'], ['bindingPerNucleonKeV', 'f64?'], ['abundancePct', 'f64?'], ['qBetaMinusKeV', 'f64?'], ['qEcKeV', 'f64?']],
  nuclear_level: [['id', 'str'], ['nuclide', 'str'], ['energyKeV', 'f64'], ['spinParity', 'str'], ['halfLifeText', 'str'], ['source', 'str']],
  decay_radiation: [['id', 'str'], ['parent', 'str'], ['decayMode', 'str'], ['radiationType', 'str'], ['energyKeV', 'f64'], ['intensityPct', 'f64?'], ['source', 'str']],
  pdg_particle: [['id', 'str'], ['mcId', 'i32'], ['name', 'str'], ['pdgId', 'str'], ['charge', 'f64'], ['spin', 'str'], ['parity', 'str'], ['cParity', 'str'], ['isospin', 'str'], ['massMeV', 'f64?'], ['massErrMeV', 'f64?'], ['widthMeV', 'f64?'], ['lifetimeS', 'f64?'], ['category', 'str'], ['edition', 'str']],
};
