// GENERATED by scripts/ingest/gen_contracts.py from scripts/ingest/schema.py — do not edit.

import { table, t } from 'spacetimedb/server';

/** One row per ingested source: query, release, checksum, licence, coverage. */
export const datasetManifest = table(
  { name: 'dataset_manifest', public: true },
  {
    id: t.string().primaryKey(),
    sourceName: t.string(),
    category: t.string(),
    sourceUrls: t.string(),
    release: t.string(),
    query: t.string(),
    retrievedAt: t.string(),
    checksum: t.string(),
    license: t.string(),
    attribution: t.string(),
    coverage: t.string(),
    units: t.string(),
    frame: t.string(),
    validationStatus: t.string(),
    rowCount: t.u32(),
    tables: t.string(),
    note: t.string(),
  },
);

/** JPL Horizons heliocentric state vectors at the pinned epoch plus SPICE constants. */
export const horizonsBody = table(
  { name: 'horizons_body', public: true },
  {
    id: t.string().primaryKey(),
    name: t.string(),
    naifId: t.i32(),
    kind: t.string(),
    parentId: t.string(),
    xM: t.f64(),
    yM: t.f64(),
    zM: t.f64(),
    vxMps: t.f64(),
    vyMps: t.f64(),
    vzMps: t.f64(),
    epochTdb: t.string(),
    epochJd: t.f64(),
    frame: t.string(),
    center: t.string(),
    radiusKm: t.option(t.f64()),
    gmKm3S2: t.option(t.f64()),
    massKg: t.option(t.f64()),
    semiMajorAxisAu: t.option(t.f64()),
    eccentricity: t.option(t.f64()),
    inclinationDeg: t.option(t.f64()),
    orbitPeriodDays: t.option(t.f64()),
    rotationPeriodHours: t.option(t.f64()),
    obliquityDeg: t.option(t.f64()),
    colorHex: t.string(),
    evidenceKind: t.string(),
  },
);

/** Sampled orbit tracks from Horizons (heliocentric for planets, parent-centric for moons). */
export const orbitSample = table(
  { name: 'orbit_sample', public: true },
  {
    id: t.string().primaryKey(),
    bodyId: t.string().index('btree'),
    center: t.string(),
    idx: t.u32(),
    jdTdb: t.f64(),
    xM: t.f64(),
    yM: t.f64(),
    zM: t.f64(),
  },
);

/** NAIF SPICE generic PCK/GM kernel values per body. */
export const spiceConstant = table(
  { name: 'spice_constant', public: true },
  {
    id: t.string().primaryKey(),
    naifId: t.i32(),
    name: t.string(),
    radiusAKm: t.option(t.f64()),
    radiusBKm: t.option(t.f64()),
    radiusCKm: t.option(t.f64()),
    gmKm3S2: t.option(t.f64()),
    poleRaDeg: t.option(t.f64()),
    poleDecDeg: t.option(t.f64()),
    pmW0Deg: t.option(t.f64()),
    pmRateDegDay: t.option(t.f64()),
    kernels: t.string(),
  },
);

/** NASA NSSDC Planetary Fact Sheet values (reference physical data). */
export const planetFact = table(
  { name: 'planet_fact', public: true },
  {
    id: t.string().primaryKey(),
    name: t.string(),
    massE24Kg: t.option(t.f64()),
    diameterKm: t.option(t.f64()),
    densityKgM3: t.option(t.f64()),
    gravityMs2: t.option(t.f64()),
    escapeVelocityKms: t.option(t.f64()),
    rotationPeriodHours: t.option(t.f64()),
    dayLengthHours: t.option(t.f64()),
    distanceFromSunE6Km: t.option(t.f64()),
    orbitalPeriodDays: t.option(t.f64()),
    orbitalVelocityKms: t.option(t.f64()),
    obliquityDeg: t.option(t.f64()),
    meanTemperatureC: t.option(t.f64()),
    surfacePressureBars: t.option(t.f64()),
    moonCount: t.option(t.u32()),
    ringSystem: t.string(),
    globalMagneticField: t.string(),
  },
);

/** Planet surface maps: PDS archive elevation grids and labelled illustrative colour maps. */
export const planetTexture = table(
  { name: 'planet_texture', public: true },
  {
    id: t.string().primaryKey(),
    bodyId: t.string(),
    kind: t.string(),
    path: t.string(),
    width: t.u32(),
    height: t.u32(),
    source: t.string(),
    sourceProductId: t.string(),
    sourceUrl: t.string(),
    projection: t.string(),
    license: t.string(),
    evidenceKind: t.string(),
  },
);

/** NASA Earthdata (CMR discovery + GIBS imagery) global layers. */
export const earthLayer = table(
  { name: 'earth_layer', public: true },
  {
    id: t.string().primaryKey(),
    title: t.string(),
    gibsLayer: t.string(),
    cmrConceptId: t.string(),
    collectionShortName: t.string(),
    timeRange: t.string(),
    path: t.string(),
    units: t.string(),
    legend: t.string(),
    evidenceKind: t.string(),
  },
);

/** Natural Earth populated places (1:110m). */
export const earthCity = table(
  { name: 'earth_city', public: true },
  {
    id: t.string().primaryKey(),
    name: t.string(),
    country: t.string(),
    latDeg: t.f64(),
    lonDeg: t.f64(),
    population: t.option(t.f64()),
    rank: t.option(t.u32()),
  },
);

/** World primary energy and electricity generation (Our World in Data / Energy Institute). */
export const energyRecord = table(
  { name: 'energy_record', public: true },
  {
    id: t.string().primaryKey(),
    entity: t.string(),
    year: t.u32(),
    metric: t.string(),
    source: t.string(),
    valueTwh: t.f64(),
  },
);

/** NOAA NCEI global land+ocean surface temperature anomaly. */
export const climateAnomaly = table(
  { name: 'climate_anomaly', public: true },
  {
    id: t.string().primaryKey(),
    year: t.u32(),
    anomalyC: t.f64(),
    baseline: t.string(),
  },
);

/** USGS FDSN event catalogue (bounded query). */
export const earthquake = table(
  { name: 'earthquake', public: true },
  {
    id: t.string().primaryKey(),
    timeIso: t.string(),
    magnitude: t.f64(),
    place: t.string(),
    latDeg: t.f64(),
    lonDeg: t.f64(),
    depthKm: t.f64(),
    eventType: t.string(),
  },
);

/** ESA Gaia DR3 quality-filtered astrometry (parallax_over_error > 10, RUWE < 1.4). */
export const gaiaStar = table(
  { name: 'gaia_star', public: true },
  {
    sourceId: t.string().primaryKey(),
    raDeg: t.f64(),
    decDeg: t.f64(),
    parallaxMas: t.f64(),
    parallaxErrorMas: t.f64(),
    pmraMasYr: t.option(t.f64()),
    pmdecMasYr: t.option(t.f64()),
    radialVelocityKms: t.option(t.f64()),
    gMag: t.f64(),
    bpRp: t.option(t.f64()),
    teffK: t.option(t.f64()),
    luminosityLsun: t.option(t.f64()),
    distancePc: t.f64(),
    xPc: t.f64(),
    yPc: t.f64(),
    zPc: t.f64(),
    glDeg: t.f64(),
    gbDeg: t.f64(),
    ruwe: t.option(t.f64()),
    refEpoch: t.f64(),
    sample: t.string(),
  },
);

/** Bright named stars (IAU WGSN names) with SIMBAD/Hipparcos astrometry. */
export const namedStar = table(
  { name: 'named_star', public: true },
  {
    id: t.string().primaryKey(),
    name: t.string(),
    simbadId: t.string(),
    raDeg: t.f64(),
    decDeg: t.f64(),
    parallaxMas: t.option(t.f64()),
    vMag: t.option(t.f64()),
    spType: t.string(),
    distancePc: t.option(t.f64()),
    xPc: t.option(t.f64()),
    yPc: t.option(t.f64()),
    zPc: t.option(t.f64()),
    gaiaDr3Id: t.string(),
    source: t.string(),
  },
);

/** NASA Exoplanet Archive pscomppars composite parameters (all confirmed planets). */
export const exoplanetSystem = table(
  { name: 'exoplanet_system', public: true },
  {
    plName: t.string().primaryKey(),
    hostname: t.string(),
    raDeg: t.f64(),
    decDeg: t.f64(),
    distancePc: t.option(t.f64()),
    orbitalPeriodDays: t.option(t.f64()),
    semiMajorAxisAu: t.option(t.f64()),
    radiusEarth: t.option(t.f64()),
    massEarth: t.option(t.f64()),
    eqTempK: t.option(t.f64()),
    eccentricity: t.option(t.f64()),
    insolationEarth: t.option(t.f64()),
    stTeffK: t.option(t.f64()),
    stRadiusSun: t.option(t.f64()),
    stMassSun: t.option(t.f64()),
    stLumLog: t.option(t.f64()),
    discoveryMethod: t.string(),
    discoveryYear: t.option(t.u32()),
    sysPlanetCount: t.option(t.u32()),
    gaiaDr3Id: t.string(),
    xPc: t.option(t.f64()),
    yPc: t.option(t.f64()),
    zPc: t.option(t.f64()),
  },
);

/** SDSS DR18 spectroscopic galaxies with Planck18 comoving distances. */
export const sdssGalaxy = table(
  { name: 'sdss_galaxy', public: true },
  {
    specObjId: t.string().primaryKey(),
    raDeg: t.f64(),
    decDeg: t.f64(),
    redshift: t.f64(),
    redshiftErr: t.f64(),
    subclass: t.string(),
    petroMagR: t.option(t.f64()),
    comovingMpc: t.f64(),
    xMpc: t.f64(),
    yMpc: t.f64(),
    zMpc: t.f64(),
  },
);

/** HEASARC LMXB/HMXB catalogues. An X-ray binary is not automatically a black hole. */
export const xrayBinary = table(
  { name: 'xray_binary', public: true },
  {
    id: t.string().primaryKey(),
    name: t.string(),
    raDeg: t.f64(),
    decDeg: t.f64(),
    glDeg: t.f64(),
    gbDeg: t.f64(),
    kind: t.string(),
    distanceKpc: t.option(t.f64()),
    orbitalPeriodDays: t.option(t.f64()),
    compactObject: t.string(),
    catalog: t.string(),
  },
);

/** Human Cell Atlas (Azul) projects touching blood / bone-marrow erythroid context. */
export const hcaProject = table(
  { name: 'hca_project', public: true },
  {
    id: t.string().primaryKey(),
    title: t.string(),
    organs: t.string(),
    cellCount: t.option(t.f64()),
    donorCount: t.option(t.u32()),
    cellTypes: t.string(),
    assays: t.string(),
    url: t.string(),
  },
);

/** NCBI Gene + Ensembl gene/transcript identifiers. */
export const geneRecord = table(
  { name: 'gene_record', public: true },
  {
    id: t.string().primaryKey(),
    geneId: t.string(),
    symbol: t.string(),
    description: t.string(),
    chromosome: t.string(),
    mapLocation: t.string(),
    assembly: t.string(),
    startPos: t.option(t.u32()),
    endPos: t.option(t.u32()),
    strand: t.i32(),
    ensemblGeneId: t.string(),
    refseqTranscript: t.string(),
    refseqProtein: t.string(),
    ensemblTranscript: t.string(),
    summary: t.string(),
  },
);

/** Coding and protein sequences (NCBI nuccore/protein and Ensembl). */
export const sequenceRecord = table(
  { name: 'sequence_record', public: true },
  {
    accession: t.string().primaryKey(),
    geneSymbol: t.string(),
    kind: t.string(),
    length: t.u32(),
    sequence: t.string(),
    source: t.string(),
    release: t.string(),
  },
);

/** Curated HBB variants: Ensembl VEP-style consequence + ClinVar classification. */
export const variantRecord = table(
  { name: 'variant_record', public: true },
  {
    id: t.string().primaryKey(),
    geneSymbol: t.string(),
    rsId: t.string(),
    clinvarId: t.string(),
    hgvsC: t.string(),
    hgvsP: t.string(),
    proteinChange: t.string(),
    chromosome: t.string(),
    positionGrch38: t.option(t.u32()),
    refAllele: t.string(),
    altAllele: t.string(),
    cdsPosition: t.option(t.u32()),
    codonRef: t.string(),
    codonAlt: t.string(),
    consequence: t.string(),
    clinicalSignificance: t.string(),
    reviewStatus: t.string(),
    conditions: t.string(),
    source: t.string(),
  },
);

/** RCSB PDB entry metadata. */
export const pdbEntry = table(
  { name: 'pdb_entry', public: true },
  {
    id: t.string().primaryKey(),
    title: t.string(),
    method: t.string(),
    resolutionA: t.option(t.f64()),
    depositDate: t.string(),
    organism: t.string(),
    description: t.string(),
    atomCount: t.u32(),
    chains: t.string(),
    ligands: t.string(),
  },
);

/** mmCIF atom_site rows (model 1, first altloc, waters dropped). Coordinates in Å. */
export const pdbAtom = table(
  { name: 'pdb_atom', public: true },
  {
    id: t.string().primaryKey(),
    entryId: t.string().index('btree'),
    serial: t.u32(),
    chain: t.string(),
    resSeq: t.i32(),
    resName: t.string(),
    atomName: t.string(),
    element: t.string(),
    x: t.f64(),
    y: t.f64(),
    z: t.f64(),
    occupancy: t.f64(),
    bFactor: t.f64(),
    hetero: t.bool(),
  },
);

/** Helix / strand ranges from mmCIF struct_conf and struct_sheet_range. */
export const pdbSecondary = table(
  { name: 'pdb_secondary', public: true },
  {
    id: t.string().primaryKey(),
    entryId: t.string(),
    chain: t.string(),
    kind: t.string(),
    startResSeq: t.i32(),
    endResSeq: t.i32(),
  },
);

/** PubChem compounds with 3D conformers. */
export const molecule = table(
  { name: 'molecule', public: true },
  {
    cid: t.u32().primaryKey(),
    name: t.string(),
    formula: t.string(),
    molecularWeight: t.f64(),
    iupacName: t.string(),
    smiles: t.string(),
    atomCount: t.u32(),
    bondCount: t.u32(),
    conformer: t.string(),
  },
);

/** PubChem 3D conformer atoms (Å). */
export const moleculeAtom = table(
  { name: 'molecule_atom', public: true },
  {
    id: t.string().primaryKey(),
    cid: t.u32().index('btree'),
    idx: t.u32(),
    element: t.string(),
    x: t.f64(),
    y: t.f64(),
    z: t.f64(),
  },
);

/** PubChem 3D conformer bonds. */
export const moleculeBond = table(
  { name: 'molecule_bond', public: true },
  {
    id: t.string().primaryKey(),
    cid: t.u32().index('btree'),
    a1: t.u32(),
    a2: t.u32(),
    order: t.u32(),
  },
);

/** NIST ASD evaluated energy levels. */
export const nistLevel = table(
  { name: 'nist_level', public: true },
  {
    id: t.string().primaryKey(),
    species: t.string(),
    configuration: t.string(),
    term: t.string(),
    j: t.string(),
    energyEv: t.f64(),
    uncertaintyEv: t.option(t.f64()),
    n: t.option(t.u32()),
    l: t.option(t.u32()),
    reference: t.string(),
  },
);

/** NIST ASD spectral lines with Einstein A coefficients where evaluated. */
export const nistLine = table(
  { name: 'nist_line', public: true },
  {
    id: t.string().primaryKey(),
    species: t.string(),
    wavelengthVacNm: t.f64(),
    akiPerS: t.option(t.f64()),
    accuracy: t.string(),
    eiEv: t.f64(),
    ekEv: t.f64(),
    lowerConf: t.string(),
    lowerTerm: t.string(),
    lowerJ: t.string(),
    upperConf: t.string(),
    upperTerm: t.string(),
    upperJ: t.string(),
    lineType: t.string(),
  },
);

/** NIST ASD ground-state ionization energies. */
export const ionizationEnergy = table(
  { name: 'ionization_energy', public: true },
  {
    species: t.string().primaryKey(),
    element: t.string(),
    ionizationEv: t.f64(),
    reference: t.string(),
  },
);

/** IAEA LiveChart ground states (ENSDF / NUBASE / AME2020). */
export const nuclide = table(
  { name: 'nuclide', public: true },
  {
    id: t.string().primaryKey(),
    z: t.u32(),
    n: t.u32(),
    a: t.u32(),
    symbol: t.string(),
    halfLifeS: t.option(t.f64()),
    halfLifeText: t.string(),
    stable: t.bool(),
    spinParity: t.string(),
    decayModes: t.string(),
    massExcessKeV: t.option(t.f64()),
    bindingPerNucleonKeV: t.option(t.f64()),
    abundancePct: t.option(t.f64()),
    qBetaMinusKeV: t.option(t.f64()),
    qEcKeV: t.option(t.f64()),
  },
);

/** IAEA LiveChart / ENSDF excited levels for the traversal nuclides. */
export const nuclearLevel = table(
  { name: 'nuclear_level', public: true },
  {
    id: t.string().primaryKey(),
    nuclide: t.string(),
    energyKeV: t.f64(),
    spinParity: t.string(),
    halfLifeText: t.string(),
    source: t.string(),
  },
);

/** IAEA LiveChart / ENSDF decay radiation (beta+, gamma, X-ray) for traversal nuclides. */
export const decayRadiation = table(
  { name: 'decay_radiation', public: true },
  {
    id: t.string().primaryKey(),
    parent: t.string(),
    decayMode: t.string(),
    radiationType: t.string(),
    energyKeV: t.f64(),
    intensityPct: t.option(t.f64()),
    source: t.string(),
  },
);

/** Particle Data Group API database: summary-table masses, widths, lifetimes. */
export const pdgParticle = table(
  { name: 'pdg_particle', public: true },
  {
    id: t.string().primaryKey(),
    mcId: t.i32(),
    name: t.string(),
    pdgId: t.string(),
    charge: t.f64(),
    spin: t.string(),
    parity: t.string(),
    cParity: t.string(),
    isospin: t.string(),
    massMeV: t.option(t.f64()),
    massErrMeV: t.option(t.f64()),
    widthMeV: t.option(t.f64()),
    lifetimeS: t.option(t.f64()),
    category: t.string(),
    edition: t.string(),
  },
);

export const scienceTables = {
  datasetManifest,
  horizonsBody,
  orbitSample,
  spiceConstant,
  planetFact,
  planetTexture,
  earthLayer,
  earthCity,
  energyRecord,
  climateAnomaly,
  earthquake,
  gaiaStar,
  namedStar,
  exoplanetSystem,
  sdssGalaxy,
  xrayBinary,
  hcaProject,
  geneRecord,
  sequenceRecord,
  variantRecord,
  pdbEntry,
  pdbAtom,
  pdbSecondary,
  molecule,
  moleculeAtom,
  moleculeBond,
  nistLevel,
  nistLine,
  ionizationEnergy,
  nuclide,
  nuclearLevel,
  decayRadiation,
  pdgParticle,
};

/** table name → [accessor, primary key, [column, type][]] for the ingest reducer. */
export const SCIENCE_SPEC: Record<string, [string, string, [string, string][]]> = {
  dataset_manifest: ['datasetManifest', 'id', [['id', 'str'], ['sourceName', 'str'], ['category', 'str'], ['sourceUrls', 'str'], ['release', 'str'], ['query', 'str'], ['retrievedAt', 'str'], ['checksum', 'str'], ['license', 'str'], ['attribution', 'str'], ['coverage', 'str'], ['units', 'str'], ['frame', 'str'], ['validationStatus', 'str'], ['rowCount', 'u32'], ['tables', 'str'], ['note', 'str']]],
  horizons_body: ['horizonsBody', 'id', [['id', 'str'], ['name', 'str'], ['naifId', 'i32'], ['kind', 'str'], ['parentId', 'str'], ['xM', 'f64'], ['yM', 'f64'], ['zM', 'f64'], ['vxMps', 'f64'], ['vyMps', 'f64'], ['vzMps', 'f64'], ['epochTdb', 'str'], ['epochJd', 'f64'], ['frame', 'str'], ['center', 'str'], ['radiusKm', 'f64?'], ['gmKm3S2', 'f64?'], ['massKg', 'f64?'], ['semiMajorAxisAu', 'f64?'], ['eccentricity', 'f64?'], ['inclinationDeg', 'f64?'], ['orbitPeriodDays', 'f64?'], ['rotationPeriodHours', 'f64?'], ['obliquityDeg', 'f64?'], ['colorHex', 'str'], ['evidenceKind', 'str']]],
  orbit_sample: ['orbitSample', 'id', [['id', 'str'], ['bodyId', 'str'], ['center', 'str'], ['idx', 'u32'], ['jdTdb', 'f64'], ['xM', 'f64'], ['yM', 'f64'], ['zM', 'f64']]],
  spice_constant: ['spiceConstant', 'id', [['id', 'str'], ['naifId', 'i32'], ['name', 'str'], ['radiusAKm', 'f64?'], ['radiusBKm', 'f64?'], ['radiusCKm', 'f64?'], ['gmKm3S2', 'f64?'], ['poleRaDeg', 'f64?'], ['poleDecDeg', 'f64?'], ['pmW0Deg', 'f64?'], ['pmRateDegDay', 'f64?'], ['kernels', 'str']]],
  planet_fact: ['planetFact', 'id', [['id', 'str'], ['name', 'str'], ['massE24Kg', 'f64?'], ['diameterKm', 'f64?'], ['densityKgM3', 'f64?'], ['gravityMs2', 'f64?'], ['escapeVelocityKms', 'f64?'], ['rotationPeriodHours', 'f64?'], ['dayLengthHours', 'f64?'], ['distanceFromSunE6Km', 'f64?'], ['orbitalPeriodDays', 'f64?'], ['orbitalVelocityKms', 'f64?'], ['obliquityDeg', 'f64?'], ['meanTemperatureC', 'f64?'], ['surfacePressureBars', 'f64?'], ['moonCount', 'u32?'], ['ringSystem', 'str'], ['globalMagneticField', 'str']]],
  planet_texture: ['planetTexture', 'id', [['id', 'str'], ['bodyId', 'str'], ['kind', 'str'], ['path', 'str'], ['width', 'u32'], ['height', 'u32'], ['source', 'str'], ['sourceProductId', 'str'], ['sourceUrl', 'str'], ['projection', 'str'], ['license', 'str'], ['evidenceKind', 'str']]],
  earth_layer: ['earthLayer', 'id', [['id', 'str'], ['title', 'str'], ['gibsLayer', 'str'], ['cmrConceptId', 'str'], ['collectionShortName', 'str'], ['timeRange', 'str'], ['path', 'str'], ['units', 'str'], ['legend', 'str'], ['evidenceKind', 'str']]],
  earth_city: ['earthCity', 'id', [['id', 'str'], ['name', 'str'], ['country', 'str'], ['latDeg', 'f64'], ['lonDeg', 'f64'], ['population', 'f64?'], ['rank', 'u32?']]],
  energy_record: ['energyRecord', 'id', [['id', 'str'], ['entity', 'str'], ['year', 'u32'], ['metric', 'str'], ['source', 'str'], ['valueTwh', 'f64']]],
  climate_anomaly: ['climateAnomaly', 'id', [['id', 'str'], ['year', 'u32'], ['anomalyC', 'f64'], ['baseline', 'str']]],
  earthquake: ['earthquake', 'id', [['id', 'str'], ['timeIso', 'str'], ['magnitude', 'f64'], ['place', 'str'], ['latDeg', 'f64'], ['lonDeg', 'f64'], ['depthKm', 'f64'], ['eventType', 'str']]],
  gaia_star: ['gaiaStar', 'sourceId', [['sourceId', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['parallaxMas', 'f64'], ['parallaxErrorMas', 'f64'], ['pmraMasYr', 'f64?'], ['pmdecMasYr', 'f64?'], ['radialVelocityKms', 'f64?'], ['gMag', 'f64'], ['bpRp', 'f64?'], ['teffK', 'f64?'], ['luminosityLsun', 'f64?'], ['distancePc', 'f64'], ['xPc', 'f64'], ['yPc', 'f64'], ['zPc', 'f64'], ['glDeg', 'f64'], ['gbDeg', 'f64'], ['ruwe', 'f64?'], ['refEpoch', 'f64'], ['sample', 'str']]],
  named_star: ['namedStar', 'id', [['id', 'str'], ['name', 'str'], ['simbadId', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['parallaxMas', 'f64?'], ['vMag', 'f64?'], ['spType', 'str'], ['distancePc', 'f64?'], ['xPc', 'f64?'], ['yPc', 'f64?'], ['zPc', 'f64?'], ['gaiaDr3Id', 'str'], ['source', 'str']]],
  exoplanet_system: ['exoplanetSystem', 'plName', [['plName', 'str'], ['hostname', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['distancePc', 'f64?'], ['orbitalPeriodDays', 'f64?'], ['semiMajorAxisAu', 'f64?'], ['radiusEarth', 'f64?'], ['massEarth', 'f64?'], ['eqTempK', 'f64?'], ['eccentricity', 'f64?'], ['insolationEarth', 'f64?'], ['stTeffK', 'f64?'], ['stRadiusSun', 'f64?'], ['stMassSun', 'f64?'], ['stLumLog', 'f64?'], ['discoveryMethod', 'str'], ['discoveryYear', 'u32?'], ['sysPlanetCount', 'u32?'], ['gaiaDr3Id', 'str'], ['xPc', 'f64?'], ['yPc', 'f64?'], ['zPc', 'f64?']]],
  sdss_galaxy: ['sdssGalaxy', 'specObjId', [['specObjId', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['redshift', 'f64'], ['redshiftErr', 'f64'], ['subclass', 'str'], ['petroMagR', 'f64?'], ['comovingMpc', 'f64'], ['xMpc', 'f64'], ['yMpc', 'f64'], ['zMpc', 'f64']]],
  xray_binary: ['xrayBinary', 'id', [['id', 'str'], ['name', 'str'], ['raDeg', 'f64'], ['decDeg', 'f64'], ['glDeg', 'f64'], ['gbDeg', 'f64'], ['kind', 'str'], ['distanceKpc', 'f64?'], ['orbitalPeriodDays', 'f64?'], ['compactObject', 'str'], ['catalog', 'str']]],
  hca_project: ['hcaProject', 'id', [['id', 'str'], ['title', 'str'], ['organs', 'str'], ['cellCount', 'f64?'], ['donorCount', 'u32?'], ['cellTypes', 'str'], ['assays', 'str'], ['url', 'str']]],
  gene_record: ['geneRecord', 'id', [['id', 'str'], ['geneId', 'str'], ['symbol', 'str'], ['description', 'str'], ['chromosome', 'str'], ['mapLocation', 'str'], ['assembly', 'str'], ['startPos', 'u32?'], ['endPos', 'u32?'], ['strand', 'i32'], ['ensemblGeneId', 'str'], ['refseqTranscript', 'str'], ['refseqProtein', 'str'], ['ensemblTranscript', 'str'], ['summary', 'str']]],
  sequence_record: ['sequenceRecord', 'accession', [['accession', 'str'], ['geneSymbol', 'str'], ['kind', 'str'], ['length', 'u32'], ['sequence', 'str'], ['source', 'str'], ['release', 'str']]],
  variant_record: ['variantRecord', 'id', [['id', 'str'], ['geneSymbol', 'str'], ['rsId', 'str'], ['clinvarId', 'str'], ['hgvsC', 'str'], ['hgvsP', 'str'], ['proteinChange', 'str'], ['chromosome', 'str'], ['positionGrch38', 'u32?'], ['refAllele', 'str'], ['altAllele', 'str'], ['cdsPosition', 'u32?'], ['codonRef', 'str'], ['codonAlt', 'str'], ['consequence', 'str'], ['clinicalSignificance', 'str'], ['reviewStatus', 'str'], ['conditions', 'str'], ['source', 'str']]],
  pdb_entry: ['pdbEntry', 'id', [['id', 'str'], ['title', 'str'], ['method', 'str'], ['resolutionA', 'f64?'], ['depositDate', 'str'], ['organism', 'str'], ['description', 'str'], ['atomCount', 'u32'], ['chains', 'str'], ['ligands', 'str']]],
  pdb_atom: ['pdbAtom', 'id', [['id', 'str'], ['entryId', 'str'], ['serial', 'u32'], ['chain', 'str'], ['resSeq', 'i32'], ['resName', 'str'], ['atomName', 'str'], ['element', 'str'], ['x', 'f64'], ['y', 'f64'], ['z', 'f64'], ['occupancy', 'f64'], ['bFactor', 'f64'], ['hetero', 'bool']]],
  pdb_secondary: ['pdbSecondary', 'id', [['id', 'str'], ['entryId', 'str'], ['chain', 'str'], ['kind', 'str'], ['startResSeq', 'i32'], ['endResSeq', 'i32']]],
  molecule: ['molecule', 'cid', [['cid', 'u32'], ['name', 'str'], ['formula', 'str'], ['molecularWeight', 'f64'], ['iupacName', 'str'], ['smiles', 'str'], ['atomCount', 'u32'], ['bondCount', 'u32'], ['conformer', 'str']]],
  molecule_atom: ['moleculeAtom', 'id', [['id', 'str'], ['cid', 'u32'], ['idx', 'u32'], ['element', 'str'], ['x', 'f64'], ['y', 'f64'], ['z', 'f64']]],
  molecule_bond: ['moleculeBond', 'id', [['id', 'str'], ['cid', 'u32'], ['a1', 'u32'], ['a2', 'u32'], ['order', 'u32']]],
  nist_level: ['nistLevel', 'id', [['id', 'str'], ['species', 'str'], ['configuration', 'str'], ['term', 'str'], ['j', 'str'], ['energyEv', 'f64'], ['uncertaintyEv', 'f64?'], ['n', 'u32?'], ['l', 'u32?'], ['reference', 'str']]],
  nist_line: ['nistLine', 'id', [['id', 'str'], ['species', 'str'], ['wavelengthVacNm', 'f64'], ['akiPerS', 'f64?'], ['accuracy', 'str'], ['eiEv', 'f64'], ['ekEv', 'f64'], ['lowerConf', 'str'], ['lowerTerm', 'str'], ['lowerJ', 'str'], ['upperConf', 'str'], ['upperTerm', 'str'], ['upperJ', 'str'], ['lineType', 'str']]],
  ionization_energy: ['ionizationEnergy', 'species', [['species', 'str'], ['element', 'str'], ['ionizationEv', 'f64'], ['reference', 'str']]],
  nuclide: ['nuclide', 'id', [['id', 'str'], ['z', 'u32'], ['n', 'u32'], ['a', 'u32'], ['symbol', 'str'], ['halfLifeS', 'f64?'], ['halfLifeText', 'str'], ['stable', 'bool'], ['spinParity', 'str'], ['decayModes', 'str'], ['massExcessKeV', 'f64?'], ['bindingPerNucleonKeV', 'f64?'], ['abundancePct', 'f64?'], ['qBetaMinusKeV', 'f64?'], ['qEcKeV', 'f64?']]],
  nuclear_level: ['nuclearLevel', 'id', [['id', 'str'], ['nuclide', 'str'], ['energyKeV', 'f64'], ['spinParity', 'str'], ['halfLifeText', 'str'], ['source', 'str']]],
  decay_radiation: ['decayRadiation', 'id', [['id', 'str'], ['parent', 'str'], ['decayMode', 'str'], ['radiationType', 'str'], ['energyKeV', 'f64'], ['intensityPct', 'f64?'], ['source', 'str']]],
  pdg_particle: ['pdgParticle', 'id', [['id', 'str'], ['mcId', 'i32'], ['name', 'str'], ['pdgId', 'str'], ['charge', 'f64'], ['spin', 'str'], ['parity', 'str'], ['cParity', 'str'], ['isospin', 'str'], ['massMeV', 'f64?'], ['massErrMeV', 'f64?'], ['widthMeV', 'f64?'], ['lifetimeS', 'f64?'], ['category', 'str'], ['edition', 'str']]],
};
