"""Generate SpacetimeDB table definitions and client row types from schema.TABLES.

Outputs (never edit by hand):
  spacetimedb/src/science.ts             module tables + column spec used by ingest reducers
  packages/engine/src/scienceTables.generated.ts  row interfaces shared by engine + web
"""
from __future__ import annotations

from pathlib import Path

from schema import TABLES

ROOT = Path(__file__).resolve().parents[2]
MODULE_OUT = ROOT / "spacetimedb" / "src" / "science.ts"
CLIENT_OUT = ROOT / "packages" / "engine" / "src" / "scienceTables.generated.ts"

BUILDER = {"str": "t.string()", "f64": "t.f64()", "i32": "t.i32()", "u32": "t.u32()", "bool": "t.bool()"}
TSTYPE = {"str": "string", "f64": "number", "i32": "number", "u32": "number", "bool": "boolean"}
HEADER = "// GENERATED by scripts/ingest/gen_contracts.py from scripts/ingest/schema.py — do not edit.\n"


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(p.title() for p in rest)


def pascal(name: str) -> str:
    return "".join(p.title() for p in name.split("_"))


def module_ts() -> str:
    out = [HEADER, "import { table, t } from 'spacetimedb/server';\n"]
    names = []
    for tname, spec in TABLES.items():
        acc = camel(tname)
        names.append((tname, acc))
        idx = set(spec.get("index", []))
        out.append(f"/** {spec['doc']} */")
        out.append(f"export const {acc} = table(\n  {{ name: '{tname}', public: true }},\n  {{")
        for i, (col, typ) in enumerate(spec["columns"]):
            base = typ.rstrip("?")
            b = BUILDER[base]
            if typ.endswith("?"):
                b = f"t.option({b})"
            if i == 0:
                b += ".primaryKey()"
            elif col in idx:
                b += ".index('btree')"
            out.append(f"    {col}: {b},")
        out.append("  },\n);\n")
    out.append("export const scienceTables = {")
    for _, acc in names:
        out.append(f"  {acc},")
    out.append("};\n")
    out.append("/** table name → [accessor, primary key, [column, type][]] for the ingest reducer. */")
    out.append("export const SCIENCE_SPEC: Record<string, [string, string, [string, string][]]> = {")
    for tname, acc in names:
        cols = TABLES[tname]["columns"]
        col_s = ", ".join(f"['{c}', '{t}']" for c, t in cols)
        out.append(f"  {tname}: ['{acc}', '{cols[0][0]}', [{col_s}]],")
    out.append("};\n")
    return "\n".join(out)


def client_ts() -> str:
    out = [HEADER]
    for tname, spec in TABLES.items():
        out.append(f"/** {spec['doc']} */")
        out.append(f"export interface {pascal(tname)}Row {{")
        for col, typ in spec["columns"]:
            ts = TSTYPE[typ.rstrip("?")]
            out.append(f"  {col}: {ts}{' | null' if typ.endswith('?') else ''};")
        out.append("}\n")
    out.append("export interface ScienceTables {")
    for tname in TABLES:
        out.append(f"  {tname}: {pascal(tname)}Row[];")
    out.append("}\n")
    out.append("export type ScienceTableName = keyof ScienceTables;\n")
    out.append("export const SCIENCE_TABLE_NAMES: ScienceTableName[] = [")
    for tname in TABLES:
        out.append(f"  '{tname}',")
    out.append("];\n")
    out.append("/** Column types per table; '?' marks nullable (SpacetimeDB option) columns. */")
    out.append("export const SCIENCE_COLUMNS: Record<ScienceTableName, [string, string][]> = {")
    for tname, spec in TABLES.items():
        col_s = ", ".join(f"['{c}', '{t}']" for c, t in spec["columns"])
        out.append(f"  {tname}: [{col_s}],")
    out.append("};\n")
    return "\n".join(out)


if __name__ == "__main__":
    MODULE_OUT.write_text(module_ts(), encoding="utf-8")
    CLIENT_OUT.parent.mkdir(parents=True, exist_ok=True)
    CLIENT_OUT.write_text(client_ts(), encoding="utf-8")
    print(f"wrote {MODULE_OUT.relative_to(ROOT)} and {CLIENT_OUT.relative_to(ROOT)} ({len(TABLES)} tables)")
