// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  branchId: __t.string().name("branch_id"),
  kind: __t.string(),
  level: __t.string(),
  revision: __t.u32(),
  inputHash: __t.string().name("input_hash"),
  payloadJson: __t.string().name("payload_json"),
  status: __t.string(),
  leaseOwnerHex: __t.string().name("lease_owner_hex"),
  leaseExpiresMicros: __t.u64().name("lease_expires_micros"),
  attempts: __t.u32(),
  resultJson: __t.string().name("result_json"),
  error: __t.string(),
  requestedBy: __t.identity().name("requested_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
