// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  commandKey: __t.string().primaryKey().name("command_key"),
  sessionId: __t.string().name("session_id"),
  branchId: __t.string().name("branch_id"),
  commandId: __t.string().name("command_id"),
  action: __t.string(),
  status: __t.string(),
  message: __t.string(),
  revision: __t.u32(),
  latestRevision: __t.u32().name("latest_revision"),
  source: __t.string(),
  sender: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
});
