// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  branchId: __t.string().name("branch_id"),
  revision: __t.u32(),
  level: __t.string(),
  promptHash: __t.string().name("prompt_hash"),
  prompt: __t.string(),
  model: __t.string(),
  assetUrl: __t.string().name("asset_url"),
  status: __t.string(),
  author: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
});
