// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  parent: __t.string(),
  decayMode: __t.string().name("decay_mode"),
  radiationType: __t.string().name("radiation_type"),
  energyKeV: __t.f64().name("energy_ke_v"),
  intensityPct: __t.option(__t.f64()).name("intensity_pct"),
  source: __t.string(),
});
