// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  branchId: __t.string().name("branch_id"),
  level: __t.string(),
  fromNode: __t.string().name("from_node"),
  toNode: __t.string().name("to_node"),
  modelId: __t.string().name("model_id"),
  modelVersion: __t.string().name("model_version"),
});
