// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  title: __t.string(),
  gibsLayer: __t.string().name("gibs_layer"),
  cmrConceptId: __t.string().name("cmr_concept_id"),
  collectionShortName: __t.string().name("collection_short_name"),
  timeRange: __t.string().name("time_range"),
  path: __t.string(),
  units: __t.string(),
  legend: __t.string(),
  evidenceKind: __t.string().name("evidence_kind"),
});
