// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  timeIso: __t.string().name("time_iso"),
  magnitude: __t.f64(),
  place: __t.string(),
  latDeg: __t.f64().name("lat_deg"),
  lonDeg: __t.f64().name("lon_deg"),
  depthKm: __t.f64().name("depth_km"),
  eventType: __t.string().name("event_type"),
});
