// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  radiusM: __t.f64().name("radius_m"),
  massKg: __t.f64().name("mass_kg"),
  albedo: __t.f64(),
  emissivity: __t.f64(),
  solarConstantWm2: __t.f64().name("solar_constant_wm_2"),
  greenhouseOffsetK: __t.f64().name("greenhouse_offset_k"),
  observedMeanSurfaceTempK: __t.f64().name("observed_mean_surface_temp_k"),
  baselinePrimaryPowerW: __t.f64().name("baseline_primary_power_w"),
  evidenceKind: __t.string().name("evidence_kind"),
  sourceId: __t.string().name("source_id"),
});
