// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  plName: __t.string().primaryKey().name("pl_name"),
  hostname: __t.string(),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  distancePc: __t.option(__t.f64()).name("distance_pc"),
  orbitalPeriodDays: __t.option(__t.f64()).name("orbital_period_days"),
  semiMajorAxisAu: __t.option(__t.f64()).name("semi_major_axis_au"),
  radiusEarth: __t.option(__t.f64()).name("radius_earth"),
  massEarth: __t.option(__t.f64()).name("mass_earth"),
  eqTempK: __t.option(__t.f64()).name("eq_temp_k"),
  eccentricity: __t.option(__t.f64()),
  insolationEarth: __t.option(__t.f64()).name("insolation_earth"),
  stTeffK: __t.option(__t.f64()).name("st_teff_k"),
  stRadiusSun: __t.option(__t.f64()).name("st_radius_sun"),
  stMassSun: __t.option(__t.f64()).name("st_mass_sun"),
  stLumLog: __t.option(__t.f64()).name("st_lum_log"),
  discoveryMethod: __t.string().name("discovery_method"),
  discoveryYear: __t.option(__t.u32()).name("discovery_year"),
  sysPlanetCount: __t.option(__t.u32()).name("sys_planet_count"),
  gaiaDr3Id: __t.string().name("gaia_dr_3_id"),
  xPc: __t.option(__t.f64()).name("x_pc"),
  yPc: __t.option(__t.f64()).name("y_pc"),
  zPc: __t.option(__t.f64()).name("z_pc"),
});
