// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  hostname: __t.string(),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  distancePc: __t.f64().name("distance_pc"),
  orbitalPeriodDays: __t.f64().name("orbital_period_days"),
  semiMajorAxisAu: __t.f64().name("semi_major_axis_au"),
  radiusEarth: __t.f64().name("radius_earth"),
  massEarth: __t.f64().name("mass_earth"),
  starTeffK: __t.f64().name("star_teff_k"),
  evidenceKind: __t.string().name("evidence_kind"),
  sourceId: __t.string().name("source_id"),
});
