// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sourceId: __t.string().primaryKey().name("source_id"),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  parallaxMas: __t.f64().name("parallax_mas"),
  parallaxErrorMas: __t.f64().name("parallax_error_mas"),
  pmraMasYr: __t.option(__t.f64()).name("pmra_mas_yr"),
  pmdecMasYr: __t.option(__t.f64()).name("pmdec_mas_yr"),
  radialVelocityKms: __t.option(__t.f64()).name("radial_velocity_kms"),
  gMag: __t.f64().name("g_mag"),
  bpRp: __t.option(__t.f64()).name("bp_rp"),
  teffK: __t.option(__t.f64()).name("teff_k"),
  luminosityLsun: __t.option(__t.f64()).name("luminosity_lsun"),
  distancePc: __t.f64().name("distance_pc"),
  xPc: __t.f64().name("x_pc"),
  yPc: __t.f64().name("y_pc"),
  zPc: __t.f64().name("z_pc"),
  glDeg: __t.f64().name("gl_deg"),
  gbDeg: __t.f64().name("gb_deg"),
  ruwe: __t.option(__t.f64()),
  refEpoch: __t.f64().name("ref_epoch"),
  sample: __t.string(),
});
