// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  geneId: __t.string().name("gene_id"),
  symbol: __t.string(),
  description: __t.string(),
  chromosome: __t.string(),
  mapLocation: __t.string().name("map_location"),
  assembly: __t.string(),
  startPos: __t.option(__t.u32()).name("start_pos"),
  endPos: __t.option(__t.u32()).name("end_pos"),
  strand: __t.i32(),
  ensemblGeneId: __t.string().name("ensembl_gene_id"),
  refseqTranscript: __t.string().name("refseq_transcript"),
  refseqProtein: __t.string().name("refseq_protein"),
  ensemblTranscript: __t.string().name("ensembl_transcript"),
  summary: __t.string(),
});
