// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  geneSymbol: __t.string().name("gene_symbol"),
  transcriptId: __t.string().name("transcript_id"),
  cdsSequence: __t.string().name("cds_sequence"),
  variantLabel: __t.string().name("variant_label"),
  rsId: __t.string().name("rs_id"),
  structureId: __t.string().name("structure_id"),
  evidenceKind: __t.string().name("evidence_kind"),
  sourceId: __t.string().name("source_id"),
});
