// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  branchId: __t.string().name("branch_id"),
  jobId: __t.string().name("job_id"),
  level: __t.string(),
  revision: __t.u32(),
  inputHash: __t.string().name("input_hash"),
  prompt: __t.string(),
  model: __t.string(),
  url: __t.string(),
  label: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
