// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  title: __t.string(),
  organs: __t.string(),
  cellCount: __t.option(__t.f64()).name("cell_count"),
  donorCount: __t.option(__t.u32()).name("donor_count"),
  cellTypes: __t.string().name("cell_types"),
  assays: __t.string(),
  url: __t.string(),
});
