// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  naifId: __t.i32().name("naif_id"),
  kind: __t.string(),
  parentId: __t.string().name("parent_id"),
  xM: __t.f64().name("x_m"),
  yM: __t.f64().name("y_m"),
  zM: __t.f64().name("z_m"),
  vxMps: __t.f64().name("vx_mps"),
  vyMps: __t.f64().name("vy_mps"),
  vzMps: __t.f64().name("vz_mps"),
  epochTdb: __t.string().name("epoch_tdb"),
  epochJd: __t.f64().name("epoch_jd"),
  frame: __t.string(),
  center: __t.string(),
  radiusKm: __t.option(__t.f64()).name("radius_km"),
  gmKm3S2: __t.option(__t.f64()).name("gm_km_3_s_2"),
  massKg: __t.option(__t.f64()).name("mass_kg"),
  semiMajorAxisAu: __t.option(__t.f64()).name("semi_major_axis_au"),
  eccentricity: __t.option(__t.f64()),
  inclinationDeg: __t.option(__t.f64()).name("inclination_deg"),
  orbitPeriodDays: __t.option(__t.f64()).name("orbit_period_days"),
  rotationPeriodHours: __t.option(__t.f64()).name("rotation_period_hours"),
  obliquityDeg: __t.option(__t.f64()).name("obliquity_deg"),
  colorHex: __t.string().name("color_hex"),
  evidenceKind: __t.string().name("evidence_kind"),
});
