// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AppendEventReducer from "./append_event_reducer";
import ArchiveBranchReducer from "./archive_branch_reducer";
import ArchiveWorldBranchReducer from "./archive_world_branch_reducer";
import ClaimAdminReducer from "./claim_admin_reducer";
import ClaimJobReducer from "./claim_job_reducer";
import ClearScienceReducer from "./clear_science_reducer";
import ClearTableReducer from "./clear_table_reducer";
import ClockControlReducer from "./clock_control_reducer";
import CompleteJobReducer from "./complete_job_reducer";
import CreateBranchReducer from "./create_branch_reducer";
import CreateSessionReducer from "./create_session_reducer";
import DescribeKindsReducer from "./describe_kinds_reducer";
import FailJobReducer from "./fail_job_reducer";
import ForkBranchReducer from "./fork_branch_reducer";
import ForkWorldBranchReducer from "./fork_world_branch_reducer";
import IngestRowsReducer from "./ingest_rows_reducer";
import JoinSessionReducer from "./join_session_reducer";
import LeaveSessionReducer from "./leave_session_reducer";
import PauseAllClocksReducer from "./pause_all_clocks_reducer";
import RebuildAclReducer from "./rebuild_acl_reducer";
import RecordConceptReducer from "./record_concept_reducer";
import RedoEventReducer from "./redo_event_reducer";
import RegisterWorkerReducer from "./register_worker_reducer";
import RenameBranchReducer from "./rename_branch_reducer";
import RenameWorldBranchReducer from "./rename_world_branch_reducer";
import RequestImagineReducer from "./request_imagine_reducer";
import ResetBranchReducer from "./reset_branch_reducer";
import SetMemberRoleReducer from "./set_member_role_reducer";
import SetPresenterReducer from "./set_presenter_reducer";
import SubmitCommandReducer from "./submit_command_reducer";
import UndoEventReducer from "./undo_event_reducer";
import UpdatePoseReducer from "./update_pose_reducer";
import UpdatePresenceReducer from "./update_presence_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AtomicLevelRow from "./atomic_level_table";
import BranchRow from "./branch_table";
import BranchEventRow from "./branch_event_table";
import CalculationJobRow from "./calculation_job_table";
import ClimateAnomalyRow from "./climate_anomaly_table";
import CommandReceiptRow from "./command_receipt_table";
import ConceptAssetRow from "./concept_asset_table";
import DatasetManifestRow from "./dataset_manifest_table";
import DecayRadiationRow from "./decay_radiation_table";
import DependencyEdgeRow from "./dependency_edge_table";
import EarthCityRow from "./earth_city_table";
import EarthLayerRow from "./earth_layer_table";
import EarthAnchorRow from "./earth_anchor_table";
import EarthConstantRow from "./earth_constant_table";
import EarthEnergyRow from "./earth_energy_table";
import EarthquakeRow from "./earthquake_table";
import EnergyRecordRow from "./energy_record_table";
import ExoplanetRow from "./exoplanet_table";
import ExoplanetSystemRow from "./exoplanet_system_table";
import GaiaStarRow from "./gaia_star_table";
import GeneRow from "./gene_table";
import GeneRecordRow from "./gene_record_table";
import GeneratedAssetRow from "./generated_asset_table";
import HcaProjectRow from "./hca_project_table";
import HorizonsBodyRow from "./horizons_body_table";
import InterventionRow from "./intervention_table";
import IonizationEnergyRow from "./ionization_energy_table";
import IsotopeRow from "./isotope_table";
import MemberAclRow from "./member_acl_table";
import ModelOutputRow from "./model_output_table";
import MoleculeRow from "./molecule_table";
import MoleculeAtomRow from "./molecule_atom_table";
import MoleculeBondRow from "./molecule_bond_table";
import NamedStarRow from "./named_star_table";
import NistLevelRow from "./nist_level_table";
import NistLineRow from "./nist_line_table";
import NuclearLevelRow from "./nuclear_level_table";
import NuclideRow from "./nuclide_table";
import OrbitSampleRow from "./orbit_sample_table";
import ParticleRow from "./particle_table";
import PdbAtomRow from "./pdb_atom_table";
import PdbEntryRow from "./pdb_entry_table";
import PdbSecondaryRow from "./pdb_secondary_table";
import PdgParticleRow from "./pdg_particle_table";
import PlanetFactRow from "./planet_fact_table";
import PlanetTextureRow from "./planet_texture_table";
import PresenceRow from "./presence_table";
import PresencePoseRow from "./presence_pose_table";
import SdssGalaxyRow from "./sdss_galaxy_table";
import SequenceRecordRow from "./sequence_record_table";
import SessionInviteRow from "./session_invite_table";
import SessionMemberRow from "./session_member_table";
import SimulationClockRow from "./simulation_clock_table";
import SimulationParameterRow from "./simulation_parameter_table";
import SolarBodyRow from "./solar_body_table";
import SourceManifestRow from "./source_manifest_table";
import SpiceConstantRow from "./spice_constant_table";
import StarRow from "./star_table";
import VariantRecordRow from "./variant_record_table";
import WorkerRow from "./worker_table";
import WorldBranchRow from "./world_branch_table";
import WorldEventRow from "./world_event_table";
import WorldSessionRow from "./world_session_table";
import XrayBinaryRow from "./xray_binary_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  atomicLevel: __table({
    name: 'atomic_level',
    indexes: [
      { accessor: 'id', name: 'atomic_level_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'atomic_level_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AtomicLevelRow),
  branch: __table({
    name: 'branch',
    indexes: [
      { accessor: 'id', name: 'branch_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'branch_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'branch_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BranchRow),
  branchEvent: __table({
    name: 'branch_event',
    indexes: [
      { accessor: 'branchId', name: 'branch_event_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'commandKey', name: 'branch_event_command_key_idx_btree', algorithm: 'btree', columns: [
        'commandKey',
      ] },
      { accessor: 'id', name: 'branch_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'branch_event_command_key_key', constraint: 'unique', columns: ['commandKey'] },
      { name: 'branch_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BranchEventRow),
  calculationJob: __table({
    name: 'calculation_job',
    indexes: [
      { accessor: 'branchId', name: 'calculation_job_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'calculation_job_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'kind', name: 'calculation_job_kind_idx_btree', algorithm: 'btree', columns: [
        'kind',
      ] },
      { accessor: 'sessionId', name: 'calculation_job_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'calculation_job_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CalculationJobRow),
  climateAnomaly: __table({
    name: 'climate_anomaly',
    indexes: [
      { accessor: 'id', name: 'climate_anomaly_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'climate_anomaly_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClimateAnomalyRow),
  commandReceipt: __table({
    name: 'command_receipt',
    indexes: [
      { accessor: 'branchId', name: 'command_receipt_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'commandKey', name: 'command_receipt_command_key_idx_btree', algorithm: 'btree', columns: [
        'commandKey',
      ] },
      { accessor: 'sessionId', name: 'command_receipt_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'command_receipt_command_key_key', constraint: 'unique', columns: ['commandKey'] },
    ],
  }, CommandReceiptRow),
  conceptAsset: __table({
    name: 'concept_asset',
    indexes: [
      { accessor: 'branchId', name: 'concept_asset_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'concept_asset_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'concept_asset_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConceptAssetRow),
  datasetManifest: __table({
    name: 'dataset_manifest',
    indexes: [
      { accessor: 'id', name: 'dataset_manifest_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dataset_manifest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatasetManifestRow),
  decayRadiation: __table({
    name: 'decay_radiation',
    indexes: [
      { accessor: 'id', name: 'decay_radiation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'decay_radiation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DecayRadiationRow),
  dependencyEdge: __table({
    name: 'dependency_edge',
    indexes: [
      { accessor: 'branchId', name: 'dependency_edge_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'dependency_edge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'dependency_edge_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'dependency_edge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DependencyEdgeRow),
  earthAnchor: __table({
    name: 'earth_anchor',
    indexes: [
      { accessor: 'id', name: 'earth_anchor_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'earth_anchor_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EarthAnchorRow),
  earthCity: __table({
    name: 'earth_city',
    indexes: [
      { accessor: 'id', name: 'earth_city_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'earth_city_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EarthCityRow),
  earthConstant: __table({
    name: 'earth_constant',
    indexes: [
      { accessor: 'id', name: 'earth_constant_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'earth_constant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EarthConstantRow),
  earthEnergy: __table({
    name: 'earth_energy',
    indexes: [
      { accessor: 'source', name: 'earth_energy_source_idx_btree', algorithm: 'btree', columns: [
        'source',
      ] },
    ],
    constraints: [
      { name: 'earth_energy_source_key', constraint: 'unique', columns: ['source'] },
    ],
  }, EarthEnergyRow),
  earthLayer: __table({
    name: 'earth_layer',
    indexes: [
      { accessor: 'id', name: 'earth_layer_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'earth_layer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EarthLayerRow),
  earthquake: __table({
    name: 'earthquake',
    indexes: [
      { accessor: 'id', name: 'earthquake_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'earthquake_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EarthquakeRow),
  energyRecord: __table({
    name: 'energy_record',
    indexes: [
      { accessor: 'id', name: 'energy_record_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'energy_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnergyRecordRow),
  exoplanet: __table({
    name: 'exoplanet',
    indexes: [
      { accessor: 'id', name: 'exoplanet_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'exoplanet_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExoplanetRow),
  exoplanetSystem: __table({
    name: 'exoplanet_system',
    indexes: [
      { accessor: 'plName', name: 'exoplanet_system_pl_name_idx_btree', algorithm: 'btree', columns: [
        'plName',
      ] },
    ],
    constraints: [
      { name: 'exoplanet_system_pl_name_key', constraint: 'unique', columns: ['plName'] },
    ],
  }, ExoplanetSystemRow),
  gaiaStar: __table({
    name: 'gaia_star',
    indexes: [
      { accessor: 'sourceId', name: 'gaia_star_source_id_idx_btree', algorithm: 'btree', columns: [
        'sourceId',
      ] },
    ],
    constraints: [
      { name: 'gaia_star_source_id_key', constraint: 'unique', columns: ['sourceId'] },
    ],
  }, GaiaStarRow),
  gene: __table({
    name: 'gene',
    indexes: [
      { accessor: 'id', name: 'gene_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gene_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GeneRow),
  geneRecord: __table({
    name: 'gene_record',
    indexes: [
      { accessor: 'id', name: 'gene_record_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gene_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GeneRecordRow),
  generatedAsset: __table({
    name: 'generated_asset',
    indexes: [
      { accessor: 'branchId', name: 'generated_asset_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'generated_asset_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'generated_asset_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'generated_asset_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GeneratedAssetRow),
  hcaProject: __table({
    name: 'hca_project',
    indexes: [
      { accessor: 'id', name: 'hca_project_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hca_project_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HcaProjectRow),
  horizonsBody: __table({
    name: 'horizons_body',
    indexes: [
      { accessor: 'id', name: 'horizons_body_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'horizons_body_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HorizonsBodyRow),
  intervention: __table({
    name: 'intervention',
    indexes: [
      { accessor: 'branchId', name: 'intervention_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'intervention_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'intervention_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'intervention_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InterventionRow),
  ionizationEnergy: __table({
    name: 'ionization_energy',
    indexes: [
      { accessor: 'species', name: 'ionization_energy_species_idx_btree', algorithm: 'btree', columns: [
        'species',
      ] },
    ],
    constraints: [
      { name: 'ionization_energy_species_key', constraint: 'unique', columns: ['species'] },
    ],
  }, IonizationEnergyRow),
  isotope: __table({
    name: 'isotope',
    indexes: [
      { accessor: 'id', name: 'isotope_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'isotope_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IsotopeRow),
  memberAcl: __table({
    name: 'member_acl',
    indexes: [
      { accessor: 'id', name: 'member_acl_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'member_acl_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'sessionId', name: 'member_acl_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'member_acl_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemberAclRow),
  modelOutput: __table({
    name: 'model_output',
    indexes: [
      { accessor: 'branchId', name: 'model_output_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'model_output_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'model_output_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'model_output_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModelOutputRow),
  molecule: __table({
    name: 'molecule',
    indexes: [
      { accessor: 'cid', name: 'molecule_cid_idx_btree', algorithm: 'btree', columns: [
        'cid',
      ] },
    ],
    constraints: [
      { name: 'molecule_cid_key', constraint: 'unique', columns: ['cid'] },
    ],
  }, MoleculeRow),
  moleculeAtom: __table({
    name: 'molecule_atom',
    indexes: [
      { accessor: 'cid', name: 'molecule_atom_cid_idx_btree', algorithm: 'btree', columns: [
        'cid',
      ] },
      { accessor: 'id', name: 'molecule_atom_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'molecule_atom_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MoleculeAtomRow),
  moleculeBond: __table({
    name: 'molecule_bond',
    indexes: [
      { accessor: 'cid', name: 'molecule_bond_cid_idx_btree', algorithm: 'btree', columns: [
        'cid',
      ] },
      { accessor: 'id', name: 'molecule_bond_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'molecule_bond_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MoleculeBondRow),
  namedStar: __table({
    name: 'named_star',
    indexes: [
      { accessor: 'id', name: 'named_star_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'named_star_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NamedStarRow),
  nistLevel: __table({
    name: 'nist_level',
    indexes: [
      { accessor: 'id', name: 'nist_level_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'nist_level_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NistLevelRow),
  nistLine: __table({
    name: 'nist_line',
    indexes: [
      { accessor: 'id', name: 'nist_line_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'nist_line_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NistLineRow),
  nuclearLevel: __table({
    name: 'nuclear_level',
    indexes: [
      { accessor: 'id', name: 'nuclear_level_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'nuclear_level_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NuclearLevelRow),
  nuclide: __table({
    name: 'nuclide',
    indexes: [
      { accessor: 'id', name: 'nuclide_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'nuclide_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NuclideRow),
  orbitSample: __table({
    name: 'orbit_sample',
    indexes: [
      { accessor: 'bodyId', name: 'orbit_sample_body_id_idx_btree', algorithm: 'btree', columns: [
        'bodyId',
      ] },
      { accessor: 'id', name: 'orbit_sample_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'orbit_sample_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrbitSampleRow),
  particle: __table({
    name: 'particle',
    indexes: [
      { accessor: 'id', name: 'particle_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'particle_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ParticleRow),
  pdbAtom: __table({
    name: 'pdb_atom',
    indexes: [
      { accessor: 'entryId', name: 'pdb_atom_entry_id_idx_btree', algorithm: 'btree', columns: [
        'entryId',
      ] },
      { accessor: 'id', name: 'pdb_atom_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pdb_atom_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PdbAtomRow),
  pdbEntry: __table({
    name: 'pdb_entry',
    indexes: [
      { accessor: 'id', name: 'pdb_entry_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pdb_entry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PdbEntryRow),
  pdbSecondary: __table({
    name: 'pdb_secondary',
    indexes: [
      { accessor: 'id', name: 'pdb_secondary_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pdb_secondary_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PdbSecondaryRow),
  pdgParticle: __table({
    name: 'pdg_particle',
    indexes: [
      { accessor: 'id', name: 'pdg_particle_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pdg_particle_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PdgParticleRow),
  planetFact: __table({
    name: 'planet_fact',
    indexes: [
      { accessor: 'id', name: 'planet_fact_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'planet_fact_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlanetFactRow),
  planetTexture: __table({
    name: 'planet_texture',
    indexes: [
      { accessor: 'id', name: 'planet_texture_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'planet_texture_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlanetTextureRow),
  presence: __table({
    name: 'presence',
    indexes: [
      { accessor: 'id', name: 'presence_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'presence_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'sessionId', name: 'presence_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'presence_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PresenceRow),
  presencePose: __table({
    name: 'presence_pose',
    indexes: [
      { accessor: 'id', name: 'presence_pose_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'presence_pose_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'sessionId', name: 'presence_pose_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'presence_pose_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PresencePoseRow),
  sdssGalaxy: __table({
    name: 'sdss_galaxy',
    indexes: [
      { accessor: 'specObjId', name: 'sdss_galaxy_spec_obj_id_idx_btree', algorithm: 'btree', columns: [
        'specObjId',
      ] },
    ],
    constraints: [
      { name: 'sdss_galaxy_spec_obj_id_key', constraint: 'unique', columns: ['specObjId'] },
    ],
  }, SdssGalaxyRow),
  sequenceRecord: __table({
    name: 'sequence_record',
    indexes: [
      { accessor: 'accession', name: 'sequence_record_accession_idx_btree', algorithm: 'btree', columns: [
        'accession',
      ] },
    ],
    constraints: [
      { name: 'sequence_record_accession_key', constraint: 'unique', columns: ['accession'] },
    ],
  }, SequenceRecordRow),
  sessionInvite: __table({
    name: 'session_invite',
    indexes: [
      { accessor: 'code', name: 'session_invite_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'sessionId', name: 'session_invite_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'session_invite_code_key', constraint: 'unique', columns: ['code'] },
    ],
  }, SessionInviteRow),
  sessionMember: __table({
    name: 'session_member',
    indexes: [
      { accessor: 'id', name: 'session_member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'session_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'sessionId', name: 'session_member_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'session_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionMemberRow),
  simulationClock: __table({
    name: 'simulation_clock',
    indexes: [
      { accessor: 'branchId', name: 'simulation_clock_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'sessionId', name: 'simulation_clock_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'simulation_clock_branch_id_key', constraint: 'unique', columns: ['branchId'] },
    ],
  }, SimulationClockRow),
  simulationParameter: __table({
    name: 'simulation_parameter',
    indexes: [
      { accessor: 'branchId', name: 'simulation_parameter_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'simulation_parameter_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'simulation_parameter_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'simulation_parameter_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SimulationParameterRow),
  solarBody: __table({
    name: 'solar_body',
    indexes: [
      { accessor: 'id', name: 'solar_body_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'solar_body_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SolarBodyRow),
  sourceManifest: __table({
    name: 'source_manifest',
    indexes: [
      { accessor: 'id', name: 'source_manifest_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'source_manifest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SourceManifestRow),
  spiceConstant: __table({
    name: 'spice_constant',
    indexes: [
      { accessor: 'id', name: 'spice_constant_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spice_constant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpiceConstantRow),
  star: __table({
    name: 'star',
    indexes: [
      { accessor: 'id', name: 'star_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'star_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StarRow),
  variantRecord: __table({
    name: 'variant_record',
    indexes: [
      { accessor: 'id', name: 'variant_record_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'variant_record_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VariantRecordRow),
  worker: __table({
    name: 'worker',
    indexes: [
      { accessor: 'identity', name: 'worker_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'kind', name: 'worker_kind_idx_btree', algorithm: 'btree', columns: [
        'kind',
      ] },
    ],
    constraints: [
      { name: 'worker_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, WorkerRow),
  worldBranch: __table({
    name: 'world_branch',
    indexes: [
      { accessor: 'id', name: 'world_branch_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'world_branch_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'world_branch_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldBranchRow),
  worldEvent: __table({
    name: 'world_event',
    indexes: [
      { accessor: 'branchId', name: 'world_event_branch_id_idx_btree', algorithm: 'btree', columns: [
        'branchId',
      ] },
      { accessor: 'id', name: 'world_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'world_event_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'world_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldEventRow),
  worldSession: __table({
    name: 'world_session',
    indexes: [
      { accessor: 'id', name: 'world_session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSessionRow),
  xrayBinary: __table({
    name: 'xray_binary',
    indexes: [
      { accessor: 'id', name: 'xray_binary_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'xray_binary_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, XrayBinaryRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("append_event", AppendEventReducer),
  __reducerSchema("archive_branch", ArchiveBranchReducer),
  __reducerSchema("archive_world_branch", ArchiveWorldBranchReducer),
  __reducerSchema("claim_admin", ClaimAdminReducer),
  __reducerSchema("claim_job", ClaimJobReducer),
  __reducerSchema("clear_science", ClearScienceReducer),
  __reducerSchema("clear_table", ClearTableReducer),
  __reducerSchema("clock_control", ClockControlReducer),
  __reducerSchema("complete_job", CompleteJobReducer),
  __reducerSchema("create_branch", CreateBranchReducer),
  __reducerSchema("create_session", CreateSessionReducer),
  __reducerSchema("describe_kinds", DescribeKindsReducer),
  __reducerSchema("fail_job", FailJobReducer),
  __reducerSchema("fork_branch", ForkBranchReducer),
  __reducerSchema("fork_world_branch", ForkWorldBranchReducer),
  __reducerSchema("ingest_rows", IngestRowsReducer),
  __reducerSchema("join_session", JoinSessionReducer),
  __reducerSchema("leave_session", LeaveSessionReducer),
  __reducerSchema("pause_all_clocks", PauseAllClocksReducer),
  __reducerSchema("rebuild_acl", RebuildAclReducer),
  __reducerSchema("record_concept", RecordConceptReducer),
  __reducerSchema("redo_event", RedoEventReducer),
  __reducerSchema("register_worker", RegisterWorkerReducer),
  __reducerSchema("rename_branch", RenameBranchReducer),
  __reducerSchema("rename_world_branch", RenameWorldBranchReducer),
  __reducerSchema("request_imagine", RequestImagineReducer),
  __reducerSchema("reset_branch", ResetBranchReducer),
  __reducerSchema("set_member_role", SetMemberRoleReducer),
  __reducerSchema("set_presenter", SetPresenterReducer),
  __reducerSchema("submit_command", SubmitCommandReducer),
  __reducerSchema("undo_event", UndoEventReducer),
  __reducerSchema("update_pose", UpdatePoseReducer),
  __reducerSchema("update_presence", UpdatePresenceReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `atomicLevel` instead. This alias will be removed in the next major version. */
    readonly "atomic_level": Omit<typeof tablesSchema.schemaType.tables["atomicLevel"], "accessorName"> & { readonly accessorName: "atomic_level" };
    /** @deprecated Use `earthAnchor` instead. This alias will be removed in the next major version. */
    readonly "earth_anchor": Omit<typeof tablesSchema.schemaType.tables["earthAnchor"], "accessorName"> & { readonly accessorName: "earth_anchor" };
    /** @deprecated Use `earthConstant` instead. This alias will be removed in the next major version. */
    readonly "earth_constant": Omit<typeof tablesSchema.schemaType.tables["earthConstant"], "accessorName"> & { readonly accessorName: "earth_constant" };
    /** @deprecated Use `earthEnergy` instead. This alias will be removed in the next major version. */
    readonly "earth_energy": Omit<typeof tablesSchema.schemaType.tables["earthEnergy"], "accessorName"> & { readonly accessorName: "earth_energy" };
    /** @deprecated Use `solarBody` instead. This alias will be removed in the next major version. */
    readonly "solar_body": Omit<typeof tablesSchema.schemaType.tables["solarBody"], "accessorName"> & { readonly accessorName: "solar_body" };
    /** @deprecated Use `sourceManifest` instead. This alias will be removed in the next major version. */
    readonly "source_manifest": Omit<typeof tablesSchema.schemaType.tables["sourceManifest"], "accessorName"> & { readonly accessorName: "source_manifest" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "atomic_level": "atomicLevel",
  "earth_anchor": "earthAnchor",
  "earth_constant": "earthConstant",
  "earth_energy": "earthEnergy",
  "solar_body": "solarBody",
  "source_manifest": "sourceManifest",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `atomicLevel` instead. This alias will be removed in the next major version. */
  readonly "atomic_level": __DbViewBase["atomicLevel"];
  /** @deprecated Use `earthAnchor` instead. This alias will be removed in the next major version. */
  readonly "earth_anchor": __DbViewBase["earthAnchor"];
  /** @deprecated Use `earthConstant` instead. This alias will be removed in the next major version. */
  readonly "earth_constant": __DbViewBase["earthConstant"];
  /** @deprecated Use `earthEnergy` instead. This alias will be removed in the next major version. */
  readonly "earth_energy": __DbViewBase["earthEnergy"];
  /** @deprecated Use `solarBody` instead. This alias will be removed in the next major version. */
  readonly "solar_body": __DbViewBase["solarBody"];
  /** @deprecated Use `sourceManifest` instead. This alias will be removed in the next major version. */
  readonly "source_manifest": __DbViewBase["sourceManifest"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `atomicLevel` instead. This alias will be removed in the next major version. */
  readonly "atomic_level": __TablesBase["atomicLevel"];
  /** @deprecated Use `earthAnchor` instead. This alias will be removed in the next major version. */
  readonly "earth_anchor": __TablesBase["earthAnchor"];
  /** @deprecated Use `earthConstant` instead. This alias will be removed in the next major version. */
  readonly "earth_constant": __TablesBase["earthConstant"];
  /** @deprecated Use `earthEnergy` instead. This alias will be removed in the next major version. */
  readonly "earth_energy": __TablesBase["earthEnergy"];
  /** @deprecated Use `solarBody` instead. This alias will be removed in the next major version. */
  readonly "solar_body": __TablesBase["solarBody"];
  /** @deprecated Use `sourceManifest` instead. This alias will be removed in the next major version. */
  readonly "source_manifest": __TablesBase["sourceManifest"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

