// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  branchId: __t.string().name("branch_id"),
  level: __t.string(),
  modelId: __t.string().name("model_id"),
  modelVersion: __t.string().name("model_version"),
  inputHash: __t.string().name("input_hash"),
  revision: __t.u32(),
  clockSeconds: __t.f64().name("clock_seconds"),
  summaryJson: __t.string().name("summary_json"),
  viewJson: __t.string().name("view_json"),
  nodesJson: __t.string().name("nodes_json"),
  warningsJson: __t.string().name("warnings_json"),
  assumptionsJson: __t.string().name("assumptions_json"),
  computedAt: __t.timestamp().name("computed_at"),
});
