// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cid: __t.u32().primaryKey(),
  name: __t.string(),
  formula: __t.string(),
  molecularWeight: __t.f64().name("molecular_weight"),
  iupacName: __t.string().name("iupac_name"),
  smiles: __t.string(),
  atomCount: __t.u32().name("atom_count"),
  bondCount: __t.u32().name("bond_count"),
  conformer: __t.string(),
});
