// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  simbadId: __t.string().name("simbad_id"),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  parallaxMas: __t.option(__t.f64()).name("parallax_mas"),
  vMag: __t.option(__t.f64()).name("v_mag"),
  spType: __t.string().name("sp_type"),
  distancePc: __t.option(__t.f64()).name("distance_pc"),
  xPc: __t.option(__t.f64()).name("x_pc"),
  yPc: __t.option(__t.f64()).name("y_pc"),
  zPc: __t.option(__t.f64()).name("z_pc"),
  gaiaDr3Id: __t.string().name("gaia_dr_3_id"),
  source: __t.string(),
});
