// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  species: __t.string(),
  configuration: __t.string(),
  term: __t.string(),
  j: __t.string(),
  energyEv: __t.f64().name("energy_ev"),
  uncertaintyEv: __t.option(__t.f64()).name("uncertainty_ev"),
  n: __t.option(__t.u32()),
  l: __t.option(__t.u32()),
  reference: __t.string(),
});
