// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  species: __t.string(),
  wavelengthVacNm: __t.f64().name("wavelength_vac_nm"),
  akiPerS: __t.option(__t.f64()).name("aki_per_s"),
  accuracy: __t.string(),
  eiEv: __t.f64().name("ei_ev"),
  ekEv: __t.f64().name("ek_ev"),
  lowerConf: __t.string().name("lower_conf"),
  lowerTerm: __t.string().name("lower_term"),
  lowerJ: __t.string().name("lower_j"),
  upperConf: __t.string().name("upper_conf"),
  upperTerm: __t.string().name("upper_term"),
  upperJ: __t.string().name("upper_j"),
  lineType: __t.string().name("line_type"),
});
