// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  z: __t.u32(),
  n: __t.u32(),
  a: __t.u32(),
  symbol: __t.string(),
  halfLifeS: __t.option(__t.f64()).name("half_life_s"),
  halfLifeText: __t.string().name("half_life_text"),
  stable: __t.bool(),
  spinParity: __t.string().name("spin_parity"),
  decayModes: __t.string().name("decay_modes"),
  massExcessKeV: __t.option(__t.f64()).name("mass_excess_ke_v"),
  bindingPerNucleonKeV: __t.option(__t.f64()).name("binding_per_nucleon_ke_v"),
  abundancePct: __t.option(__t.f64()).name("abundance_pct"),
  qBetaMinusKeV: __t.option(__t.f64()).name("q_beta_minus_ke_v"),
  qEcKeV: __t.option(__t.f64()).name("q_ec_ke_v"),
});
