// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  bodyId: __t.string().name("body_id"),
  center: __t.string(),
  idx: __t.u32(),
  jdTdb: __t.f64().name("jd_tdb"),
  xM: __t.f64().name("x_m"),
  yM: __t.f64().name("y_m"),
  zM: __t.f64().name("z_m"),
});
