// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  entryId: __t.string().name("entry_id"),
  serial: __t.u32(),
  chain: __t.string(),
  resSeq: __t.i32().name("res_seq"),
  resName: __t.string().name("res_name"),
  atomName: __t.string().name("atom_name"),
  element: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  occupancy: __t.f64(),
  bFactor: __t.f64().name("b_factor"),
  hetero: __t.bool(),
});
