// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  mcId: __t.i32().name("mc_id"),
  name: __t.string(),
  pdgId: __t.string().name("pdg_id"),
  charge: __t.f64(),
  spin: __t.string(),
  parity: __t.string(),
  cParity: __t.string().name("c_parity"),
  isospin: __t.string(),
  massMeV: __t.option(__t.f64()).name("mass_me_v"),
  massErrMeV: __t.option(__t.f64()).name("mass_err_me_v"),
  widthMeV: __t.option(__t.f64()).name("width_me_v"),
  lifetimeS: __t.option(__t.f64()).name("lifetime_s"),
  category: __t.string(),
  edition: __t.string(),
});
