// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  massE24Kg: __t.option(__t.f64()).name("mass_e_24_kg"),
  diameterKm: __t.option(__t.f64()).name("diameter_km"),
  densityKgM3: __t.option(__t.f64()).name("density_kg_m_3"),
  gravityMs2: __t.option(__t.f64()).name("gravity_ms_2"),
  escapeVelocityKms: __t.option(__t.f64()).name("escape_velocity_kms"),
  rotationPeriodHours: __t.option(__t.f64()).name("rotation_period_hours"),
  dayLengthHours: __t.option(__t.f64()).name("day_length_hours"),
  distanceFromSunE6Km: __t.option(__t.f64()).name("distance_from_sun_e_6_km"),
  orbitalPeriodDays: __t.option(__t.f64()).name("orbital_period_days"),
  orbitalVelocityKms: __t.option(__t.f64()).name("orbital_velocity_kms"),
  obliquityDeg: __t.option(__t.f64()).name("obliquity_deg"),
  meanTemperatureC: __t.option(__t.f64()).name("mean_temperature_c"),
  surfacePressureBars: __t.option(__t.f64()).name("surface_pressure_bars"),
  moonCount: __t.option(__t.u32()).name("moon_count"),
  ringSystem: __t.string().name("ring_system"),
  globalMagneticField: __t.string().name("global_magnetic_field"),
});
