// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  bodyId: __t.string().name("body_id"),
  kind: __t.string(),
  path: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
  source: __t.string(),
  sourceProductId: __t.string().name("source_product_id"),
  sourceUrl: __t.string().name("source_url"),
  projection: __t.string(),
  license: __t.string(),
  evidenceKind: __t.string().name("evidence_kind"),
});
