// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  role: __t.string(),
  branchId: __t.string().name("branch_id"),
  stop: __t.string(),
  selectedId: __t.string().name("selected_id"),
  following: __t.bool(),
  online: __t.bool(),
  lastSeen: __t.timestamp().name("last_seen"),
});
