// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  identity: __t.identity(),
  stop: __t.string(),
  px: __t.f64(),
  py: __t.f64(),
  pz: __t.f64(),
  tx: __t.f64(),
  ty: __t.f64(),
  tz: __t.f64(),
  color: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
