// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  branchId: __t.string(),
  revision: __t.u32(),
  level: __t.string(),
  promptHash: __t.string(),
  prompt: __t.string(),
  model: __t.string(),
  assetUrl: __t.string(),
  status: __t.string(),
};
