// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  specObjId: __t.string().primaryKey().name("spec_obj_id"),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  redshift: __t.f64(),
  redshiftErr: __t.f64().name("redshift_err"),
  subclass: __t.string(),
  petroMagR: __t.option(__t.f64()).name("petro_mag_r"),
  comovingMpc: __t.f64().name("comoving_mpc"),
  xMpc: __t.f64().name("x_mpc"),
  yMpc: __t.f64().name("y_mpc"),
  zMpc: __t.f64().name("z_mpc"),
});
