// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  accession: __t.string().primaryKey(),
  geneSymbol: __t.string().name("gene_symbol"),
  kind: __t.string(),
  length: __t.u32(),
  sequence: __t.string(),
  source: __t.string(),
  release: __t.string(),
});
