// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  branchId: __t.string().primaryKey().name("branch_id"),
  sessionId: __t.string().name("session_id"),
  running: __t.bool(),
  rate: __t.f64(),
  simSeconds: __t.f64().name("sim_seconds"),
  revision: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
