// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  horizonsId: __t.string().name("horizons_id"),
  kind: __t.string(),
  radiusM: __t.f64().name("radius_m"),
  massKg: __t.f64().name("mass_kg"),
  xM: __t.f64().name("x_m"),
  yM: __t.f64().name("y_m"),
  zM: __t.f64().name("z_m"),
  vxMps: __t.f64().name("vx_mps"),
  vyMps: __t.f64().name("vy_mps"),
  vzMps: __t.f64().name("vz_mps"),
  luminosityW: __t.f64().name("luminosity_w"),
  orbitPeriodDays: __t.f64().name("orbit_period_days"),
  colorHex: __t.string().name("color_hex"),
  epoch: __t.string(),
  frame: __t.string(),
  evidenceKind: __t.string().name("evidence_kind"),
  sourceId: __t.string().name("source_id"),
});
