// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  naifId: __t.i32().name("naif_id"),
  name: __t.string(),
  radiusAKm: __t.option(__t.f64()).name("radius_a_km"),
  radiusBKm: __t.option(__t.f64()).name("radius_b_km"),
  radiusCKm: __t.option(__t.f64()).name("radius_c_km"),
  gmKm3S2: __t.option(__t.f64()).name("gm_km_3_s_2"),
  poleRaDeg: __t.option(__t.f64()).name("pole_ra_deg"),
  poleDecDeg: __t.option(__t.f64()).name("pole_dec_deg"),
  pmW0Deg: __t.option(__t.f64()).name("pm_w_0_deg"),
  pmRateDegDay: __t.option(__t.f64()).name("pm_rate_deg_day"),
  kernels: __t.string(),
});
