// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  distanceM: __t.f64().name("distance_m"),
  parallaxMas: __t.f64().name("parallax_mas"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  luminosityW: __t.f64().name("luminosity_w"),
  teffK: __t.f64().name("teff_k"),
  colorHex: __t.string().name("color_hex"),
  evidenceKind: __t.string().name("evidence_kind"),
  sourceId: __t.string().name("source_id"),
});
