// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  id: __t.u32(),
  owner: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

export const AtomicLevel = __t.object("AtomicLevel", {
  id: __t.string(),
  species: __t.string(),
  n: __t.u32(),
  l: __t.u32(),
  energyEv: __t.f64(),
  term: __t.string(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type AtomicLevel = __Infer<typeof AtomicLevel>;

export const Branch = __t.object("Branch", {
  id: __t.string(),
  name: __t.string(),
  owner: __t.identity(),
  baselineId: __t.string(),
  parentBranchId: __t.string(),
  forkRevision: __t.u32(),
  head: __t.u32(),
  cursor: __t.u32(),
  revision: __t.u32(),
  seed: __t.u32(),
  archived: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Branch = __Infer<typeof Branch>;

export const BranchEvent = __t.object("BranchEvent", {
  id: __t.string(),
  branchId: __t.string(),
  seq: __t.u32(),
  commandKey: __t.string(),
  commandId: __t.string(),
  action: __t.string(),
  targetId: __t.string(),
  parametersJson: __t.string(),
  modelId: __t.string(),
  modelVersion: __t.string(),
  summaryJson: __t.string(),
  author: __t.identity(),
  createdAt: __t.timestamp(),
});
export type BranchEvent = __Infer<typeof BranchEvent>;

export const CalculationJob = __t.object("CalculationJob", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  kind: __t.string(),
  level: __t.string(),
  revision: __t.u32(),
  inputHash: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  leaseOwnerHex: __t.string(),
  leaseExpiresMicros: __t.u64(),
  attempts: __t.u32(),
  resultJson: __t.string(),
  error: __t.string(),
  requestedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CalculationJob = __Infer<typeof CalculationJob>;

export const ClimateAnomaly = __t.object("ClimateAnomaly", {
  id: __t.string(),
  year: __t.u32(),
  anomalyC: __t.f64(),
  baseline: __t.string(),
});
export type ClimateAnomaly = __Infer<typeof ClimateAnomaly>;

export const ClockSchedule = __t.object("ClockSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ClockSchedule = __Infer<typeof ClockSchedule>;

export const CommandReceipt = __t.object("CommandReceipt", {
  commandKey: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  commandId: __t.string(),
  action: __t.string(),
  status: __t.string(),
  message: __t.string(),
  revision: __t.u32(),
  latestRevision: __t.u32(),
  source: __t.string(),
  sender: __t.identity(),
  createdAt: __t.timestamp(),
});
export type CommandReceipt = __Infer<typeof CommandReceipt>;

export const ConceptAsset = __t.object("ConceptAsset", {
  id: __t.string(),
  branchId: __t.string(),
  revision: __t.u32(),
  level: __t.string(),
  promptHash: __t.string(),
  prompt: __t.string(),
  model: __t.string(),
  assetUrl: __t.string(),
  status: __t.string(),
  author: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ConceptAsset = __Infer<typeof ConceptAsset>;

export const DatasetManifest = __t.object("DatasetManifest", {
  id: __t.string(),
  sourceName: __t.string(),
  category: __t.string(),
  sourceUrls: __t.string(),
  release: __t.string(),
  query: __t.string(),
  retrievedAt: __t.string(),
  checksum: __t.string(),
  license: __t.string(),
  attribution: __t.string(),
  coverage: __t.string(),
  units: __t.string(),
  frame: __t.string(),
  validationStatus: __t.string(),
  rowCount: __t.u32(),
  tables: __t.string(),
  note: __t.string(),
});
export type DatasetManifest = __Infer<typeof DatasetManifest>;

export const DecayRadiation = __t.object("DecayRadiation", {
  id: __t.string(),
  parent: __t.string(),
  decayMode: __t.string(),
  radiationType: __t.string(),
  energyKeV: __t.f64(),
  intensityPct: __t.option(__t.f64()),
  source: __t.string(),
});
export type DecayRadiation = __Infer<typeof DecayRadiation>;

export const DependencyEdge = __t.object("DependencyEdge", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  level: __t.string(),
  fromNode: __t.string(),
  toNode: __t.string(),
  modelId: __t.string(),
  modelVersion: __t.string(),
});
export type DependencyEdge = __Infer<typeof DependencyEdge>;

export const EarthAnchor = __t.object("EarthAnchor", {
  id: __t.string(),
  name: __t.string(),
  latDeg: __t.f64(),
  lonDeg: __t.f64(),
  weight: __t.f64(),
});
export type EarthAnchor = __Infer<typeof EarthAnchor>;

export const EarthCity = __t.object("EarthCity", {
  id: __t.string(),
  name: __t.string(),
  country: __t.string(),
  latDeg: __t.f64(),
  lonDeg: __t.f64(),
  population: __t.option(__t.f64()),
  rank: __t.option(__t.u32()),
});
export type EarthCity = __Infer<typeof EarthCity>;

export const EarthConstant = __t.object("EarthConstant", {
  id: __t.string(),
  radiusM: __t.f64(),
  massKg: __t.f64(),
  albedo: __t.f64(),
  emissivity: __t.f64(),
  solarConstantWm2: __t.f64(),
  greenhouseOffsetK: __t.f64(),
  observedMeanSurfaceTempK: __t.f64(),
  baselinePrimaryPowerW: __t.f64(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type EarthConstant = __Infer<typeof EarthConstant>;

export const EarthEnergy = __t.object("EarthEnergy", {
  source: __t.string(),
  capacityW: __t.f64(),
  generationW: __t.f64(),
  capacityFactor: __t.f64(),
});
export type EarthEnergy = __Infer<typeof EarthEnergy>;

export const EarthLayer = __t.object("EarthLayer", {
  id: __t.string(),
  title: __t.string(),
  gibsLayer: __t.string(),
  cmrConceptId: __t.string(),
  collectionShortName: __t.string(),
  timeRange: __t.string(),
  path: __t.string(),
  units: __t.string(),
  legend: __t.string(),
  evidenceKind: __t.string(),
});
export type EarthLayer = __Infer<typeof EarthLayer>;

export const Earthquake = __t.object("Earthquake", {
  id: __t.string(),
  timeIso: __t.string(),
  magnitude: __t.f64(),
  place: __t.string(),
  latDeg: __t.f64(),
  lonDeg: __t.f64(),
  depthKm: __t.f64(),
  eventType: __t.string(),
});
export type Earthquake = __Infer<typeof Earthquake>;

export const EnergyRecord = __t.object("EnergyRecord", {
  id: __t.string(),
  entity: __t.string(),
  year: __t.u32(),
  metric: __t.string(),
  source: __t.string(),
  valueTwh: __t.f64(),
});
export type EnergyRecord = __Infer<typeof EnergyRecord>;

export const Exoplanet = __t.object("Exoplanet", {
  id: __t.string(),
  name: __t.string(),
  hostname: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  distancePc: __t.f64(),
  orbitalPeriodDays: __t.f64(),
  semiMajorAxisAu: __t.f64(),
  radiusEarth: __t.f64(),
  massEarth: __t.f64(),
  starTeffK: __t.f64(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type Exoplanet = __Infer<typeof Exoplanet>;

export const ExoplanetSystem = __t.object("ExoplanetSystem", {
  plName: __t.string(),
  hostname: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  distancePc: __t.option(__t.f64()),
  orbitalPeriodDays: __t.option(__t.f64()),
  semiMajorAxisAu: __t.option(__t.f64()),
  radiusEarth: __t.option(__t.f64()),
  massEarth: __t.option(__t.f64()),
  eqTempK: __t.option(__t.f64()),
  eccentricity: __t.option(__t.f64()),
  insolationEarth: __t.option(__t.f64()),
  stTeffK: __t.option(__t.f64()),
  stRadiusSun: __t.option(__t.f64()),
  stMassSun: __t.option(__t.f64()),
  stLumLog: __t.option(__t.f64()),
  discoveryMethod: __t.string(),
  discoveryYear: __t.option(__t.u32()),
  sysPlanetCount: __t.option(__t.u32()),
  gaiaDr3Id: __t.string(),
  xPc: __t.option(__t.f64()),
  yPc: __t.option(__t.f64()),
  zPc: __t.option(__t.f64()),
});
export type ExoplanetSystem = __Infer<typeof ExoplanetSystem>;

export const GaiaStar = __t.object("GaiaStar", {
  sourceId: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  parallaxMas: __t.f64(),
  parallaxErrorMas: __t.f64(),
  pmraMasYr: __t.option(__t.f64()),
  pmdecMasYr: __t.option(__t.f64()),
  radialVelocityKms: __t.option(__t.f64()),
  gMag: __t.f64(),
  bpRp: __t.option(__t.f64()),
  teffK: __t.option(__t.f64()),
  luminosityLsun: __t.option(__t.f64()),
  distancePc: __t.f64(),
  xPc: __t.f64(),
  yPc: __t.f64(),
  zPc: __t.f64(),
  glDeg: __t.f64(),
  gbDeg: __t.f64(),
  ruwe: __t.option(__t.f64()),
  refEpoch: __t.f64(),
  sample: __t.string(),
});
export type GaiaStar = __Infer<typeof GaiaStar>;

export const Gene = __t.object("Gene", {
  id: __t.string(),
  geneSymbol: __t.string(),
  transcriptId: __t.string(),
  cdsSequence: __t.string(),
  variantLabel: __t.string(),
  rsId: __t.string(),
  structureId: __t.string(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type Gene = __Infer<typeof Gene>;

export const GeneRecord = __t.object("GeneRecord", {
  id: __t.string(),
  geneId: __t.string(),
  symbol: __t.string(),
  description: __t.string(),
  chromosome: __t.string(),
  mapLocation: __t.string(),
  assembly: __t.string(),
  startPos: __t.option(__t.u32()),
  endPos: __t.option(__t.u32()),
  strand: __t.i32(),
  ensemblGeneId: __t.string(),
  refseqTranscript: __t.string(),
  refseqProtein: __t.string(),
  ensemblTranscript: __t.string(),
  summary: __t.string(),
});
export type GeneRecord = __Infer<typeof GeneRecord>;

export const GeneratedAsset = __t.object("GeneratedAsset", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  jobId: __t.string(),
  level: __t.string(),
  revision: __t.u32(),
  inputHash: __t.string(),
  prompt: __t.string(),
  model: __t.string(),
  url: __t.string(),
  label: __t.string(),
  createdAt: __t.timestamp(),
});
export type GeneratedAsset = __Infer<typeof GeneratedAsset>;

export const HcaProject = __t.object("HcaProject", {
  id: __t.string(),
  title: __t.string(),
  organs: __t.string(),
  cellCount: __t.option(__t.f64()),
  donorCount: __t.option(__t.u32()),
  cellTypes: __t.string(),
  assays: __t.string(),
  url: __t.string(),
});
export type HcaProject = __Infer<typeof HcaProject>;

export const HorizonsBody = __t.object("HorizonsBody", {
  id: __t.string(),
  name: __t.string(),
  naifId: __t.i32(),
  kind: __t.string(),
  parentId: __t.string(),
  xM: __t.f64(),
  yM: __t.f64(),
  zM: __t.f64(),
  vxMps: __t.f64(),
  vyMps: __t.f64(),
  vzMps: __t.f64(),
  epochTdb: __t.string(),
  epochJd: __t.f64(),
  frame: __t.string(),
  center: __t.string(),
  radiusKm: __t.option(__t.f64()),
  gmKm3S2: __t.option(__t.f64()),
  massKg: __t.option(__t.f64()),
  semiMajorAxisAu: __t.option(__t.f64()),
  eccentricity: __t.option(__t.f64()),
  inclinationDeg: __t.option(__t.f64()),
  orbitPeriodDays: __t.option(__t.f64()),
  rotationPeriodHours: __t.option(__t.f64()),
  obliquityDeg: __t.option(__t.f64()),
  colorHex: __t.string(),
  evidenceKind: __t.string(),
});
export type HorizonsBody = __Infer<typeof HorizonsBody>;

export const Intervention = __t.object("Intervention", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  interventionId: __t.string(),
  level: __t.string(),
  kind: __t.string(),
  label: __t.string(),
  paramsJson: __t.string(),
  createdSeq: __t.u32(),
  updatedSeq: __t.u32(),
});
export type Intervention = __Infer<typeof Intervention>;

export const IonizationEnergy = __t.object("IonizationEnergy", {
  species: __t.string(),
  element: __t.string(),
  ionizationEv: __t.f64(),
  reference: __t.string(),
});
export type IonizationEnergy = __Infer<typeof IonizationEnergy>;

export const Isotope = __t.object("Isotope", {
  id: __t.string(),
  symbol: __t.string(),
  z: __t.u32(),
  a: __t.u32(),
  bindingEnergyPerNucleonMev: __t.f64(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type Isotope = __Infer<typeof Isotope>;

export const MemberAcl = __t.object("MemberAcl", {
  id: __t.string(),
  sessionId: __t.string(),
  identity: __t.identity(),
  role: __t.string(),
});
export type MemberAcl = __Infer<typeof MemberAcl>;

export const ModelOutput = __t.object("ModelOutput", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  level: __t.string(),
  modelId: __t.string(),
  modelVersion: __t.string(),
  inputHash: __t.string(),
  revision: __t.u32(),
  clockSeconds: __t.f64(),
  summaryJson: __t.string(),
  viewJson: __t.string(),
  nodesJson: __t.string(),
  warningsJson: __t.string(),
  assumptionsJson: __t.string(),
  computedAt: __t.timestamp(),
});
export type ModelOutput = __Infer<typeof ModelOutput>;

export const Molecule = __t.object("Molecule", {
  cid: __t.u32(),
  name: __t.string(),
  formula: __t.string(),
  molecularWeight: __t.f64(),
  iupacName: __t.string(),
  smiles: __t.string(),
  atomCount: __t.u32(),
  bondCount: __t.u32(),
  conformer: __t.string(),
});
export type Molecule = __Infer<typeof Molecule>;

export const MoleculeAtom = __t.object("MoleculeAtom", {
  id: __t.string(),
  cid: __t.u32(),
  idx: __t.u32(),
  element: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
});
export type MoleculeAtom = __Infer<typeof MoleculeAtom>;

export const MoleculeBond = __t.object("MoleculeBond", {
  id: __t.string(),
  cid: __t.u32(),
  a1: __t.u32(),
  a2: __t.u32(),
  order: __t.u32(),
});
export type MoleculeBond = __Infer<typeof MoleculeBond>;

export const NamedStar = __t.object("NamedStar", {
  id: __t.string(),
  name: __t.string(),
  simbadId: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  parallaxMas: __t.option(__t.f64()),
  vMag: __t.option(__t.f64()),
  spType: __t.string(),
  distancePc: __t.option(__t.f64()),
  xPc: __t.option(__t.f64()),
  yPc: __t.option(__t.f64()),
  zPc: __t.option(__t.f64()),
  gaiaDr3Id: __t.string(),
  source: __t.string(),
});
export type NamedStar = __Infer<typeof NamedStar>;

export const NistLevel = __t.object("NistLevel", {
  id: __t.string(),
  species: __t.string(),
  configuration: __t.string(),
  term: __t.string(),
  j: __t.string(),
  energyEv: __t.f64(),
  uncertaintyEv: __t.option(__t.f64()),
  n: __t.option(__t.u32()),
  l: __t.option(__t.u32()),
  reference: __t.string(),
});
export type NistLevel = __Infer<typeof NistLevel>;

export const NistLine = __t.object("NistLine", {
  id: __t.string(),
  species: __t.string(),
  wavelengthVacNm: __t.f64(),
  akiPerS: __t.option(__t.f64()),
  accuracy: __t.string(),
  eiEv: __t.f64(),
  ekEv: __t.f64(),
  lowerConf: __t.string(),
  lowerTerm: __t.string(),
  lowerJ: __t.string(),
  upperConf: __t.string(),
  upperTerm: __t.string(),
  upperJ: __t.string(),
  lineType: __t.string(),
});
export type NistLine = __Infer<typeof NistLine>;

export const NuclearLevel = __t.object("NuclearLevel", {
  id: __t.string(),
  nuclide: __t.string(),
  energyKeV: __t.f64(),
  spinParity: __t.string(),
  halfLifeText: __t.string(),
  source: __t.string(),
});
export type NuclearLevel = __Infer<typeof NuclearLevel>;

export const Nuclide = __t.object("Nuclide", {
  id: __t.string(),
  z: __t.u32(),
  n: __t.u32(),
  a: __t.u32(),
  symbol: __t.string(),
  halfLifeS: __t.option(__t.f64()),
  halfLifeText: __t.string(),
  stable: __t.bool(),
  spinParity: __t.string(),
  decayModes: __t.string(),
  massExcessKeV: __t.option(__t.f64()),
  bindingPerNucleonKeV: __t.option(__t.f64()),
  abundancePct: __t.option(__t.f64()),
  qBetaMinusKeV: __t.option(__t.f64()),
  qEcKeV: __t.option(__t.f64()),
});
export type Nuclide = __Infer<typeof Nuclide>;

export const OrbitSample = __t.object("OrbitSample", {
  id: __t.string(),
  bodyId: __t.string(),
  center: __t.string(),
  idx: __t.u32(),
  jdTdb: __t.f64(),
  xM: __t.f64(),
  yM: __t.f64(),
  zM: __t.f64(),
});
export type OrbitSample = __Infer<typeof OrbitSample>;

export const Particle = __t.object("Particle", {
  id: __t.string(),
  name: __t.string(),
  symbol: __t.string(),
  pdgId: __t.i32(),
  massMev: __t.f64(),
  charge: __t.f64(),
  spinJ: __t.f64(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type Particle = __Infer<typeof Particle>;

export const PdbAtom = __t.object("PdbAtom", {
  id: __t.string(),
  entryId: __t.string(),
  serial: __t.u32(),
  chain: __t.string(),
  resSeq: __t.i32(),
  resName: __t.string(),
  atomName: __t.string(),
  element: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  occupancy: __t.f64(),
  bFactor: __t.f64(),
  hetero: __t.bool(),
});
export type PdbAtom = __Infer<typeof PdbAtom>;

export const PdbEntry = __t.object("PdbEntry", {
  id: __t.string(),
  title: __t.string(),
  method: __t.string(),
  resolutionA: __t.option(__t.f64()),
  depositDate: __t.string(),
  organism: __t.string(),
  description: __t.string(),
  atomCount: __t.u32(),
  chains: __t.string(),
  ligands: __t.string(),
});
export type PdbEntry = __Infer<typeof PdbEntry>;

export const PdbSecondary = __t.object("PdbSecondary", {
  id: __t.string(),
  entryId: __t.string(),
  chain: __t.string(),
  kind: __t.string(),
  startResSeq: __t.i32(),
  endResSeq: __t.i32(),
});
export type PdbSecondary = __Infer<typeof PdbSecondary>;

export const PdgParticle = __t.object("PdgParticle", {
  id: __t.string(),
  mcId: __t.i32(),
  name: __t.string(),
  pdgId: __t.string(),
  charge: __t.f64(),
  spin: __t.string(),
  parity: __t.string(),
  cParity: __t.string(),
  isospin: __t.string(),
  massMeV: __t.option(__t.f64()),
  massErrMeV: __t.option(__t.f64()),
  widthMeV: __t.option(__t.f64()),
  lifetimeS: __t.option(__t.f64()),
  category: __t.string(),
  edition: __t.string(),
});
export type PdgParticle = __Infer<typeof PdgParticle>;

export const PlanetFact = __t.object("PlanetFact", {
  id: __t.string(),
  name: __t.string(),
  massE24Kg: __t.option(__t.f64()),
  diameterKm: __t.option(__t.f64()),
  densityKgM3: __t.option(__t.f64()),
  gravityMs2: __t.option(__t.f64()),
  escapeVelocityKms: __t.option(__t.f64()),
  rotationPeriodHours: __t.option(__t.f64()),
  dayLengthHours: __t.option(__t.f64()),
  distanceFromSunE6Km: __t.option(__t.f64()),
  orbitalPeriodDays: __t.option(__t.f64()),
  orbitalVelocityKms: __t.option(__t.f64()),
  obliquityDeg: __t.option(__t.f64()),
  meanTemperatureC: __t.option(__t.f64()),
  surfacePressureBars: __t.option(__t.f64()),
  moonCount: __t.option(__t.u32()),
  ringSystem: __t.string(),
  globalMagneticField: __t.string(),
});
export type PlanetFact = __Infer<typeof PlanetFact>;

export const PlanetTexture = __t.object("PlanetTexture", {
  id: __t.string(),
  bodyId: __t.string(),
  kind: __t.string(),
  path: __t.string(),
  width: __t.u32(),
  height: __t.u32(),
  source: __t.string(),
  sourceProductId: __t.string(),
  sourceUrl: __t.string(),
  projection: __t.string(),
  license: __t.string(),
  evidenceKind: __t.string(),
});
export type PlanetTexture = __Infer<typeof PlanetTexture>;

export const Presence = __t.object("Presence", {
  id: __t.string(),
  sessionId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  branchId: __t.string(),
  stop: __t.string(),
  selectedId: __t.string(),
  following: __t.bool(),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const PresencePose = __t.object("PresencePose", {
  id: __t.string(),
  sessionId: __t.string(),
  identity: __t.identity(),
  stop: __t.string(),
  px: __t.f64(),
  py: __t.f64(),
  pz: __t.f64(),
  tx: __t.f64(),
  ty: __t.f64(),
  tz: __t.f64(),
  color: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PresencePose = __Infer<typeof PresencePose>;

export const SdssGalaxy = __t.object("SdssGalaxy", {
  specObjId: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  redshift: __t.f64(),
  redshiftErr: __t.f64(),
  subclass: __t.string(),
  petroMagR: __t.option(__t.f64()),
  comovingMpc: __t.f64(),
  xMpc: __t.f64(),
  yMpc: __t.f64(),
  zMpc: __t.f64(),
});
export type SdssGalaxy = __Infer<typeof SdssGalaxy>;

export const SequenceRecord = __t.object("SequenceRecord", {
  accession: __t.string(),
  geneSymbol: __t.string(),
  kind: __t.string(),
  length: __t.u32(),
  sequence: __t.string(),
  source: __t.string(),
  release: __t.string(),
});
export type SequenceRecord = __Infer<typeof SequenceRecord>;

export const SessionInvite = __t.object("SessionInvite", {
  code: __t.string(),
  sessionId: __t.string(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type SessionInvite = __Infer<typeof SessionInvite>;

export const SessionMember = __t.object("SessionMember", {
  id: __t.string(),
  sessionId: __t.string(),
  identity: __t.identity(),
  role: __t.string(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
});
export type SessionMember = __Infer<typeof SessionMember>;

export const SimulationClock = __t.object("SimulationClock", {
  branchId: __t.string(),
  sessionId: __t.string(),
  running: __t.bool(),
  rate: __t.f64(),
  simSeconds: __t.f64(),
  revision: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type SimulationClock = __Infer<typeof SimulationClock>;

export const SimulationParameter = __t.object("SimulationParameter", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  key: __t.string(),
  level: __t.string(),
  valueJson: __t.string(),
});
export type SimulationParameter = __Infer<typeof SimulationParameter>;

export const SolarBody = __t.object("SolarBody", {
  id: __t.string(),
  name: __t.string(),
  horizonsId: __t.string(),
  kind: __t.string(),
  radiusM: __t.f64(),
  massKg: __t.f64(),
  xM: __t.f64(),
  yM: __t.f64(),
  zM: __t.f64(),
  vxMps: __t.f64(),
  vyMps: __t.f64(),
  vzMps: __t.f64(),
  luminosityW: __t.f64(),
  orbitPeriodDays: __t.f64(),
  colorHex: __t.string(),
  epoch: __t.string(),
  frame: __t.string(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type SolarBody = __Infer<typeof SolarBody>;

export const SourceManifest = __t.object("SourceManifest", {
  id: __t.string(),
  sourceName: __t.string(),
  sourceUrl: __t.string(),
  release: __t.string(),
  rowCount: __t.u32(),
  note: __t.string(),
});
export type SourceManifest = __Infer<typeof SourceManifest>;

export const SpiceConstant = __t.object("SpiceConstant", {
  id: __t.string(),
  naifId: __t.i32(),
  name: __t.string(),
  radiusAKm: __t.option(__t.f64()),
  radiusBKm: __t.option(__t.f64()),
  radiusCKm: __t.option(__t.f64()),
  gmKm3S2: __t.option(__t.f64()),
  poleRaDeg: __t.option(__t.f64()),
  poleDecDeg: __t.option(__t.f64()),
  pmW0Deg: __t.option(__t.f64()),
  pmRateDegDay: __t.option(__t.f64()),
  kernels: __t.string(),
});
export type SpiceConstant = __Infer<typeof SpiceConstant>;

export const Star = __t.object("Star", {
  id: __t.string(),
  name: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  distanceM: __t.f64(),
  parallaxMas: __t.f64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  luminosityW: __t.f64(),
  teffK: __t.f64(),
  colorHex: __t.string(),
  evidenceKind: __t.string(),
  sourceId: __t.string(),
});
export type Star = __Infer<typeof Star>;

export const VariantRecord = __t.object("VariantRecord", {
  id: __t.string(),
  geneSymbol: __t.string(),
  rsId: __t.string(),
  clinvarId: __t.string(),
  hgvsC: __t.string(),
  hgvsP: __t.string(),
  proteinChange: __t.string(),
  chromosome: __t.string(),
  positionGrch38: __t.option(__t.u32()),
  refAllele: __t.string(),
  altAllele: __t.string(),
  cdsPosition: __t.option(__t.u32()),
  codonRef: __t.string(),
  codonAlt: __t.string(),
  consequence: __t.string(),
  clinicalSignificance: __t.string(),
  reviewStatus: __t.string(),
  conditions: __t.string(),
  source: __t.string(),
});
export type VariantRecord = __Infer<typeof VariantRecord>;

export const Worker = __t.object("Worker", {
  identity: __t.identity(),
  kind: __t.string(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Worker = __Infer<typeof Worker>;

export const WorldBranch = __t.object("WorldBranch", {
  id: __t.string(),
  sessionId: __t.string(),
  name: __t.string(),
  baselineId: __t.string(),
  parentBranchId: __t.string(),
  forkRevision: __t.u32(),
  head: __t.u32(),
  cursor: __t.u32(),
  revision: __t.u32(),
  seed: __t.u32(),
  kardashevLevel: __t.u32(),
  barrowLevel: __t.u32(),
  archived: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorldBranch = __Infer<typeof WorldBranch>;

export const WorldEvent = __t.object("WorldEvent", {
  id: __t.string(),
  sessionId: __t.string(),
  branchId: __t.string(),
  seq: __t.u32(),
  commandId: __t.string(),
  action: __t.string(),
  targetId: __t.string(),
  parametersJson: __t.string(),
  source: __t.string(),
  author: __t.identity(),
  createdAt: __t.timestamp(),
});
export type WorldEvent = __Infer<typeof WorldEvent>;

export const WorldSession = __t.object("WorldSession", {
  id: __t.string(),
  name: __t.string(),
  owner: __t.identity(),
  mainBranchId: __t.string(),
  presenterHex: __t.string(),
  createdAt: __t.timestamp(),
});
export type WorldSession = __Infer<typeof WorldSession>;

export const XrayBinary = __t.object("XrayBinary", {
  id: __t.string(),
  name: __t.string(),
  raDeg: __t.f64(),
  decDeg: __t.f64(),
  glDeg: __t.f64(),
  gbDeg: __t.f64(),
  kind: __t.string(),
  distanceKpc: __t.option(__t.f64()),
  orbitalPeriodDays: __t.option(__t.f64()),
  compactObject: __t.string(),
  catalog: __t.string(),
});
export type XrayBinary = __Infer<typeof XrayBinary>;

