// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  stop: __t.string(),
  px: __t.f64(),
  py: __t.f64(),
  pz: __t.f64(),
  tx: __t.f64(),
  ty: __t.f64(),
  tz: __t.f64(),
  color: __t.string(),
};
