// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  geneSymbol: __t.string().name("gene_symbol"),
  rsId: __t.string().name("rs_id"),
  clinvarId: __t.string().name("clinvar_id"),
  hgvsC: __t.string().name("hgvs_c"),
  hgvsP: __t.string().name("hgvs_p"),
  proteinChange: __t.string().name("protein_change"),
  chromosome: __t.string(),
  positionGrch38: __t.option(__t.u32()).name("position_grch_38"),
  refAllele: __t.string().name("ref_allele"),
  altAllele: __t.string().name("alt_allele"),
  cdsPosition: __t.option(__t.u32()).name("cds_position"),
  codonRef: __t.string().name("codon_ref"),
  codonAlt: __t.string().name("codon_alt"),
  consequence: __t.string(),
  clinicalSignificance: __t.string().name("clinical_significance"),
  reviewStatus: __t.string().name("review_status"),
  conditions: __t.string(),
  source: __t.string(),
});
