// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  branchId: __t.string().name("branch_id"),
  seq: __t.u32(),
  commandId: __t.string().name("command_id"),
  action: __t.string(),
  targetId: __t.string().name("target_id"),
  parametersJson: __t.string().name("parameters_json"),
  source: __t.string(),
  author: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
});
