// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  name: __t.string(),
  baselineId: __t.string().name("baseline_id"),
  parentBranchId: __t.string().name("parent_branch_id"),
  forkRevision: __t.u32().name("fork_revision"),
  head: __t.u32(),
  cursor: __t.u32(),
  revision: __t.u32(),
  seed: __t.u32(),
  kardashevLevel: __t.u32().name("kardashev_level"),
  barrowLevel: __t.u32().name("barrow_level"),
  archived: __t.bool(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
