// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  raDeg: __t.f64().name("ra_deg"),
  decDeg: __t.f64().name("dec_deg"),
  glDeg: __t.f64().name("gl_deg"),
  gbDeg: __t.f64().name("gb_deg"),
  kind: __t.string(),
  distanceKpc: __t.option(__t.f64()).name("distance_kpc"),
  orbitalPeriodDays: __t.option(__t.f64()).name("orbital_period_days"),
  compactObject: __t.string().name("compact_object"),
  catalog: __t.string(),
});
