// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendEventReducer from "../append_event_reducer";
import ArchiveBranchReducer from "../archive_branch_reducer";
import ArchiveWorldBranchReducer from "../archive_world_branch_reducer";
import ClaimAdminReducer from "../claim_admin_reducer";
import ClaimJobReducer from "../claim_job_reducer";
import ClearScienceReducer from "../clear_science_reducer";
import ClearTableReducer from "../clear_table_reducer";
import ClockControlReducer from "../clock_control_reducer";
import CompleteJobReducer from "../complete_job_reducer";
import CreateBranchReducer from "../create_branch_reducer";
import CreateSessionReducer from "../create_session_reducer";
import DescribeKindsReducer from "../describe_kinds_reducer";
import FailJobReducer from "../fail_job_reducer";
import ForkBranchReducer from "../fork_branch_reducer";
import ForkWorldBranchReducer from "../fork_world_branch_reducer";
import IngestRowsReducer from "../ingest_rows_reducer";
import JoinSessionReducer from "../join_session_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import PauseAllClocksReducer from "../pause_all_clocks_reducer";
import RebuildAclReducer from "../rebuild_acl_reducer";
import RecordConceptReducer from "../record_concept_reducer";
import RedoEventReducer from "../redo_event_reducer";
import RegisterWorkerReducer from "../register_worker_reducer";
import RenameBranchReducer from "../rename_branch_reducer";
import RenameWorldBranchReducer from "../rename_world_branch_reducer";
import RequestImagineReducer from "../request_imagine_reducer";
import ResetBranchReducer from "../reset_branch_reducer";
import SetMemberRoleReducer from "../set_member_role_reducer";
import SetPresenterReducer from "../set_presenter_reducer";
import SubmitCommandReducer from "../submit_command_reducer";
import UndoEventReducer from "../undo_event_reducer";
import UpdatePoseReducer from "../update_pose_reducer";
import UpdatePresenceReducer from "../update_presence_reducer";

export type AppendEventParams = __Infer<typeof AppendEventReducer>;
export type ArchiveBranchParams = __Infer<typeof ArchiveBranchReducer>;
export type ArchiveWorldBranchParams = __Infer<typeof ArchiveWorldBranchReducer>;
export type ClaimAdminParams = __Infer<typeof ClaimAdminReducer>;
export type ClaimJobParams = __Infer<typeof ClaimJobReducer>;
export type ClearScienceParams = __Infer<typeof ClearScienceReducer>;
export type ClearTableParams = __Infer<typeof ClearTableReducer>;
export type ClockControlParams = __Infer<typeof ClockControlReducer>;
export type CompleteJobParams = __Infer<typeof CompleteJobReducer>;
export type CreateBranchParams = __Infer<typeof CreateBranchReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type DescribeKindsParams = __Infer<typeof DescribeKindsReducer>;
export type FailJobParams = __Infer<typeof FailJobReducer>;
export type ForkBranchParams = __Infer<typeof ForkBranchReducer>;
export type ForkWorldBranchParams = __Infer<typeof ForkWorldBranchReducer>;
export type IngestRowsParams = __Infer<typeof IngestRowsReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type PauseAllClocksParams = __Infer<typeof PauseAllClocksReducer>;
export type RebuildAclParams = __Infer<typeof RebuildAclReducer>;
export type RecordConceptParams = __Infer<typeof RecordConceptReducer>;
export type RedoEventParams = __Infer<typeof RedoEventReducer>;
export type RegisterWorkerParams = __Infer<typeof RegisterWorkerReducer>;
export type RenameBranchParams = __Infer<typeof RenameBranchReducer>;
export type RenameWorldBranchParams = __Infer<typeof RenameWorldBranchReducer>;
export type RequestImagineParams = __Infer<typeof RequestImagineReducer>;
export type ResetBranchParams = __Infer<typeof ResetBranchReducer>;
export type SetMemberRoleParams = __Infer<typeof SetMemberRoleReducer>;
export type SetPresenterParams = __Infer<typeof SetPresenterReducer>;
export type SubmitCommandParams = __Infer<typeof SubmitCommandReducer>;
export type UndoEventParams = __Infer<typeof UndoEventReducer>;
export type UpdatePoseParams = __Infer<typeof UpdatePoseReducer>;
export type UpdatePresenceParams = __Infer<typeof UpdatePresenceReducer>;

